/**
 * `virtual:aihu-server-entry` — the request-time server bundle's entry module,
 * for `output: 'ssr'`.
 *
 * ## Why a virtual module and not an emitted file
 *
 * The shipped adapters build their worker by writing a STRING to disk at
 * `closeBundle`, after Vite has finished. That is why they cannot render
 * anything: the string is outside the module graph, so it can neither import
 * `virtual:aihu-routes` nor have a `.aihu` file compiled for it. The route
 * manifest they emit instead gives every route a 404 placeholder.
 *
 * `@aihu/adapter-cloudflare`'s docblock blames "the non-serializable `module()`
 * thunk" for that. It is not the reason. `fileToRouteDefinition`
 * (`vite-plugin.ts`) builds `module: () => Promise.resolve({ default: null })` —
 * there was never a loadable module to serialize, so no amount of adapter-side
 * work could have produced one. Route modules have to come from
 * `virtual:aihu-routes`, from INSIDE the graph.
 *
 * So this module IS the worker entry, declared as a build input of the `ssr`
 * environment. `import routes from 'virtual:aihu-routes'` then resolves to real
 * chunks (`module: () => import("./assets/pages-<hash>.js")`), `.aihu` files
 * compile to the SERVER target automatically (`aihuCompilerPlugin` reads
 * `this.environment.config.consumer === 'server'`), and one `vite build`
 * produces both environments.
 *
 * LOAD-BEARING and non-obvious: a `virtual:` id works as a build entry ONLY via
 * `rollupOptions.input`. `build.ssr: 'virtual:…'` fails with
 * `[UNRESOLVED_ENTRY]`.
 *
 * ## Why the registry is built at module init
 *
 * `__aihu_schild` runs inside the compiled string fast path, which is
 * SYNCHRONOUS. Every child module must already be in hand before a render
 * begins, so the awaiting happens once, at module scope, not per request.
 * `ServerRouterOptions.children` is typed as a resolved map for exactly this
 * reason.
 */

import type { AihuConfig } from './config.ts'

export const SERVER_ENTRY_VIRTUAL_ID = 'virtual:aihu-server-entry'
export const SERVER_ENTRY_RESOLVED_ID = '\0virtual:aihu-server-entry'

/**
 * What an adapter's `serverEntry()` is handed. Small on purpose: the adapter
 * contributes a platform wrapper, it does not get to rewrite the framework's
 * half of the entry.
 */
export interface ServerEntryContext {
  /**
   * The identifier the generated prelude binds the request handler to. Call it
   * as `handler(request)` — it takes a `Request` and returns a
   * `Promise<Response>`, matching `ServerRouter.handle`.
   *
   * NOTE, honestly: there is no platform/`env` parameter. `ServerRouter.handle`
   * accepts a `Request` and nothing else, so an adapter cannot thread Worker
   * bindings through it today. Emitting a second argument that the framework
   * silently drops would be worse than the gap.
   */
  readonly handler: string
  /** The resolved `AihuConfig` passed to `viteAihuPlugin`. */
  readonly config: AihuConfig
}

/** The binding name the prelude exports and an adapter wrapper calls. */
const HANDLER = 'handler'

/**
 * Build the source of `virtual:aihu-server-entry`.
 *
 * `adapterSource` is the adapter's `serverEntry()` text, appended verbatim
 * after the prelude — it is expected to contain the platform's own
 * `export default`. When no adapter contributes one, the prelude's named
 * `handler` export stands alone and is usable by hand.
 */
export function buildServerEntrySource(adapterSource?: string): string {
  const prelude = [
    '// AUTO-GENERATED by @aihu/app — virtual:aihu-server-entry. Do not edit.',
    "import { createServerRouter } from '@aihu/router/server'",
    "import { buildChildRegistry } from '@aihu/server'",
    "import routes from 'virtual:aihu-routes'",
    "import __components from 'virtual:aihu-server-components'",
    '',
    '// Resolve every child module ONCE, at module init. `__aihu_schild` runs',
    '// inside the synchronous compiled string path, so nothing can be awaited',
    '// mid-render.',
    'const __loaded = await Promise.all(',
    '  Object.entries(__components).map(async ([tag, load]) => ({ tag, mod: await load() })),',
    ')',
    '',
    "// Key on the module's own `__aihu_tag__` — what `defineElement` actually",
    '// registers, and what `__aihu_schild` looks up. The generated registry key',
    '// is derived from the FILE and is only used to choose which modules to',
    "// bundle; `@aihu/app`'s SSG path keys on `__aihu_tag__` for the same",
    "// reason, and the two paths disagreeing would ship one module's markup and",
    "// upgrade it with another's on hydrate.",
    'const __discovered = []',
    'for (const { tag, mod } of __loaded) {',
    '  const real = mod.__aihu_tag__',
    '  if (real === undefined) {',
    // Emitted as CONCATENATION rather than a template literal purely so this
    // file contains no `${…}` inside a plain string — which a linter cannot
    // tell apart from a template literal someone forgot to backtick.
    '    console.warn(',
    "      '[@aihu/app] ssr output: component <' + tag + '> exports no __aihu_tag__, so it ' +",
    "        'cannot be resolved by tag and will render as an empty element.',",
    '    )',
    '    continue',
    '  }',
    '  __discovered.push({ tag: real, module: mod })',
    '}',
    '',
    'const __children = buildChildRegistry(__discovered, (m) => console.warn(m))',
    'const __router = createServerRouter(routes, { children: __children })',
    '',
    '/** Request handler: `(request: Request) => Promise<Response>`. */',
    `export const ${HANDLER} = (request) => __router.handle(request)`,
  ].join('\n')

  return adapterSource ? `${prelude}\n\n${adapterSource}\n` : `${prelude}\n`
}

/** The handler identifier the prelude exports. Exported so tests cannot drift. */
export const SERVER_ENTRY_HANDLER = HANDLER
