// Type declarations for virtual modules used by @aihu/app.

declare module 'virtual:aihu-routes' {
  import type { RouteDefinition } from '@aihu/router'

  const routes: RouteDefinition[]
  export default routes
}

declare module 'virtual:aihu-components' {
  /**
   * Normalized component tag → lazy loader. Importing a loader registers that
   * component's custom element as a side effect. Generated by `@aihu/router`'s
   * Vite plugin (O1b). Empty object when no components exist.
   */
  const registry: Record<string, () => Promise<unknown>>
  export default registry
}

/**
 * F1: runtime hook published by @aihu/app's client bootstrap (client.ts, module
 * top level) so COMPILER-EMITTED code can register a route's referenced
 * components. The nested `<$outlet>` boundary (`createOutletBoundary` in
 * packages/compiler/src/codegen/emit.rs) has no build-graph import of
 * virtual:aihu-components, so it calls this global optional-chained:
 *
 *   Promise.all([m.route.module(), ...(globalThis.__aihuRegisterRouteComponents?.(m.route) ?? [])])
 *
 * `undefined` when @aihu/app is not loaded (standalone @aihu/router app) — the
 * outlet then skips component registration. The parameter is structural
 * (`{ components? }`, not RouteDefinition) — the emitted JS passes the matched
 * route object and the hook only reads its `components` tags.
 */
declare var __aihuRegisterRouteComponents:
  | ((route: { components?: readonly string[] }) => Promise<unknown>[])
  | undefined

declare module 'virtual:aihu-layouts' {
  /**
   * Layout name (from `@route { layout: "<name>" }`) → runtime entry. `load()`
   * dynamically imports the layout SFC (registering its `aihu-layout-<name>`
   * custom element as a side effect); `tag` is that element's name. Generated by
   * `@aihu/router`'s Vite plugin (`genL`). Empty object when no layouts exist.
   */
  const layouts: Record<string, { tag: string; load: () => Promise<unknown> }>
  export default layouts
}
