// Type declarations for virtual modules used by @aihu/app.

declare module 'virtual:aihu-routes' {
  import type { RouteDefinition } from '@aihu/router'

  const routes: RouteDefinition[]
  export default routes
}

declare module 'virtual:aihu-layouts' {
  /**
   * Layout name (from `@route { layout: "<name>" }`) → runtime entry. `load()`
   * dynamically imports the layout SFC (registering its `aihu-layout-<name>`
   * custom element as a side effect); `tag` is that element's name. Generated by
   * `@aihu/router`'s Vite plugin (`genL`). Empty object when no layouts exist.
   */
  const layouts: Record<string, { tag: string; load: () => Promise<unknown> }>
  export default layouts
}
