/**
 * GENERATED by scripts/gen-gallery.ts — DO NOT EDIT BY HAND.
 *
 * Cookbook rows are derived from packages/mcp/src/cookbook-index.json (the real
 * cookbook/*.aihu corpus + frontmatter + source). Governed rows are derived from
 * examples/<name>/coverage.manifest.json (the 9 founder-ratified governed
 * examples; cookbook/COVERAGE-MATRIX.md). Re-run: `bun scripts/gen-gallery.ts`.
 *
 * Coverage: 20 cookbook recipes, 9 governed examples.
 */

/** A cookbook recipe: one real, compiled `.aihu` component + its frontmatter. */
export interface Recipe {
  readonly id: string
  readonly filename: string
  readonly title: string
  readonly type: string
  readonly description: string
  readonly constructs: readonly string[]
  readonly packages: readonly string[]
  readonly concerns: readonly string[]
  readonly since: string
  /** Preset label when the recipe is wired into the in-browser playground. */
  readonly playground?: string
  readonly related: readonly string[]
  readonly antiPatterns: readonly string[]
  /** The full `.aihu` source of the recipe. */
  readonly source: string
}

/** A governed example: a founder-ratified, CI-built subsystem exemplar. */
export interface Governed {
  readonly id: string
  readonly example: string
  readonly subsystem: string
  readonly sources: readonly string[]
  readonly exercises: readonly string[]
  readonly ci: string
}

export const COOKBOOK: readonly Recipe[] = [
  {
    id: 'agent-weather',
    filename: 'agent-weather.aihu',
    title: 'Agent Weather',
    type: 'agent',
    description:
      'Agent-surface async fetch — prop city and action fetchForecast carry expose/describe so MCP agents can read and invoke them.',
    constructs: [
      'prop',
      'prop.expose',
      'prop.describe',
      'state',
      'action',
      'action.expose',
      'action.describe',
      'group',
      'if',
      'elseif',
      'else',
      'on:click',
      'interpolation',
    ],
    packages: [],
    concerns: ['state', 'events', 'governance'],
    since: '0.5.0',
    playground: 'Agent',
    related: ['fetch-resource', 'guard-ui'],
    antiPatterns: [
      "Do not mark a mutating action expose: 'read' — the expose tier must match what the action does; fetchForecast writes state, so it is 'read write'.",
      'Do not throw from an exposed action for ordinary failures — set an error state the agent can read back.',
    ],
    source: `// agent-weather — agent-surface pattern: prop city + action fetchForecast with expose/describe

@state {
  let city = prop({
    default: 'London',
    describe: 'City name to retrieve weather forecast for',
    expose: 'read',
  })

  let forecast = state('')
  let loading = state(false)
  let errorMsg = state('')

  const fetchForecast = action(
    { describe: 'Fetch the latest weather forecast for the current city',
      expose: 'read write' },
    async () => {
        loading = true
        errorMsg = ''
        try {
          const res = await fetch(\`/api/weather?city=\${encodeURIComponent(city)}\`)
          if (!res.ok) throw new Error(\`HTTP \${res.status}\`)
          forecast = await res.text()
        } catch (e) {
          errorMsg = (e as Error).message
        } finally {
          loading = false
        }
      })
}

@template {
  <div class="weather-agent">
    <h2 class="title">Weather — {city}</h2>
    <group if={loading}>
      <p class="loading">Fetching forecast…</p>
    </group><group elseif={errorMsg}>
      <p class="error">{errorMsg}</p>
    </group><group elseif={forecast}>
      <p class="forecast">{forecast}</p>
    </group><group else>
      <p class="prompt">Press Refresh to load forecast.</p>
    </group>
    <button on:click={fetchForecast} class="refresh-btn" disabled={loading}>
      Refresh
    </button>
  </div>
}

@style {
  .weather-agent { padding: 1.5rem; max-width: 22rem; border: 1px solid var(--border, #ccc); border-radius: 6px; }
  .title { margin: 0 0 1rem; font-size: 1.2rem; }
  .loading { color: var(--info, #036); }
  .error { color: var(--error, #c00); }
  .forecast { font-size: 1rem; line-height: 1.5; }
  .prompt { color: var(--muted, #888); font-style: italic; }
  .refresh-btn { margin-top: 0.75rem; padding: 0.4rem 1rem; cursor: pointer; border: 1px solid var(--border, #ccc); border-radius: 4px; }
  .refresh-btn:disabled { opacity: 0.5; cursor: not-allowed; }
}
`,
  },
  {
    id: 'aihu-accordion',
    filename: 'aihu-accordion.aihu',
    title: 'Accordion',
    type: 'container',
    description:
      'Accordion — each/key over prop-provided items, show toggles the open panel, aria-expanded tracks state.',
    constructs: [
      'prop',
      'state',
      'action',
      'each',
      'key',
      'show',
      'group',
      'on:click',
      'interpolation',
    ],
    packages: [],
    concerns: ['state', 'a11y'],
    since: '0.5.0',
    related: ['aihu-tabs', 'aihu-modal'],
    antiPatterns: [
      'Do not drive frequently-toggled panels with if= — show keeps DOM and internal state alive; if= tears down and rebuilds.',
    ],
    source: `// accordion — prop items (array) + action toggle, each over items, show for content

@state {
  const items = prop({
    default: [
        { id: '1', title: 'First item', content: 'Content for the first panel.' },
        { id: '2', title: 'Second item', content: 'Content for the second panel.' },
        { id: '3', title: 'Third item', content: 'Content for the third panel.' },
      ],
  })

  let openId = state('')

  const toggle = action((id: string) => {
      openId = openId === id ? '' : id
    })
}

@template {
  <div class="accordion" role="list">
    <group each={item of items} key={item.id}>
      <div class="accordion-item" role="listitem">
        <button
          class={['accordion-header', openId === item.id && 'open']}
          on:click={() => toggle(item.id)}
          aria-expanded={openId === item.id}
        >
          <span>{item.title}</span>
          <span class="chevron">{openId === item.id ? '▲' : '▼'}</span>
        </button>
        <div show={openId === item.id} class="accordion-body">
          <p>{item.content}</p>
        </div>
      </div>
    </group>
  </div>
}

@style {
  .accordion { border: 1px solid var(--border, #ccc); border-radius: 6px; overflow: hidden; max-width: 32rem; }
  .accordion-item { border-bottom: 1px solid var(--border, #ccc); }
  .accordion-item:last-child { border-bottom: none; }
  .accordion-header { width: 100%; display: flex; justify-content: space-between; align-items: center; padding: 0.75rem 1rem; background: none; border: none; cursor: pointer; font-size: 1rem; text-align: left; }
  .accordion-header.open { background: var(--accent-subtle, #eef); }
  .chevron { font-size: 0.7rem; color: var(--muted, #888); }
  .accordion-body { padding: 0.75rem 1rem; background: var(--panel-bg, #fafafa); }
  .accordion-body p { margin: 0; }
  [hidden] { display: none; }
}
`,
  },
  {
    id: 'aihu-clock',
    filename: 'aihu-clock.aihu',
    title: 'Clock',
    type: 'display',
    description:
      'Real-time clock — onMount starts the interval, onDispose clears it; tick runs through an action.',
    constructs: ['state', 'action', 'onMount', 'onDispose', 'interpolation'],
    packages: [],
    concerns: ['state'],
    since: '0.5.0',
    related: ['aihu-toast'],
    antiPatterns: [
      'Do not start timers at @state top level — setup also runs during SSR; start them in onMount and always clear them in onDispose.',
    ],
    source: `// clock — real-time clock: onMount starts setInterval, onDispose clears it

@state {
  let hours = state('00')
  let minutes = state('00')
  let seconds = state('00')
  let _timerId: number | null = null

  const tick = action(() => {
      const now = new Date()
      hours = String(now.getHours()).padStart(2, '0')
      minutes = String(now.getMinutes()).padStart(2, '0')
      seconds = String(now.getSeconds()).padStart(2, '0')
    })

  onMount(() => {
      tick()
      _timerId = setInterval(() => tick(), 1000) as unknown as number
    })
  onDispose(() => {
      if (_timerId !== null) {
        clearInterval(_timerId)
        _timerId = null
      }
    })
}

@template {
  <div class="clock" role="timer" aria-live="off">
    <span class="digit">{hours}</span>
    <span class="sep">:</span>
    <span class="digit">{minutes}</span>
    <span class="sep">:</span>
    <span class="digit seconds">{seconds}</span>
  </div>
}

@style {
  .clock { display: flex; align-items: center; gap: 0.1rem; font-size: 3rem; font-variant-numeric: tabular-nums; font-family: monospace; padding: 1rem; }
  .digit { background: var(--digit-bg, #111); color: var(--digit-fg, #0f0); padding: 0.1em 0.2em; border-radius: 4px; min-width: 1.5ch; text-align: center; }
  .sep { color: var(--muted, #888); padding: 0 0.05em; }
  .seconds { color: var(--seconds-fg, #0af); }
}
`,
  },
  {
    id: 'aihu-controller',
    filename: 'aihu-controller.aihu',
    title: 'Controller',
    type: 'display',
    description:
      'controller() intrinsic — a ResizeObserver reactive controller with hostConnected/hostDisconnected lifecycle, writes routed through an action.',
    constructs: ['state', 'action', 'controller', 'controller.describe', 'interpolation'],
    packages: [],
    concerns: ['state', 'events'],
    since: '0.5.0',
    related: ['infinite-scroll'],
    antiPatterns: [
      'Do not write state directly inside a controller body (C561) — controllers are derivations; route writes through an action.',
    ],
    source: `// controller — controller() intrinsic wrapping a ResizeObserver reactive controller

@state {
  let width = state(0)
  let height = state(0)

  const setSize = action((w: number, h: number) => {
    width = w
    height = h
  })

  const resizeObserver = controller({ describe: 'Tracks host size via ResizeObserver' }, () => {
    let observer: ResizeObserver | null = null
    return {
      hostConnected: () => {
        observer = new ResizeObserver((entries) => {
          const rect = entries[0]?.contentRect
          setSize(Math.round(rect?.width ?? 0), Math.round(rect?.height ?? 0))
        })
        observer.observe((ctx.host as ShadowRoot).host)
      },
      hostDisconnected: () => {
        observer?.disconnect()
        observer = null
      },
    }
  })
}

@template {
  <div class="controller-demo">
    <div class="resize-box">
      <p class="dim">Width: <strong>{width}px</strong></p>
      <p class="dim">Height: <strong>{height}px</strong></p>
      <p class="hint">Resize the component to see updates.</p>
    </div>
  </div>
}

@style {
  .controller-demo { padding: 1rem; resize: both; overflow: auto; border: 2px dashed var(--border, #ccc); min-width: 200px; min-height: 100px; }
  .resize-box { display: grid; gap: 0.25rem; }
  .dim { margin: 0; font-family: monospace; font-size: 0.9rem; }
  .hint { margin: 0.5rem 0 0; font-size: 0.8rem; color: var(--muted, #888); }
}
`,
  },
  {
    id: 'aihu-counter',
    filename: 'aihu-counter.aihu',
    title: 'Counter',
    type: 'display',
    description:
      'Minimal reactive counter — prop-backed count with increment/decrement/reset actions.',
    constructs: ['prop', 'action', 'on:click', 'interpolation'],
    packages: [],
    concerns: ['state', 'events'],
    since: '0.5.0',
    playground: 'Counter',
    related: ['agent-weather', 'aihu-tabs'],
    antiPatterns: [
      "Do not reach for state() when the value is part of the component's public surface — prop() makes it host-settable and attribute-visible.",
    ],
    source: `// counter — prop count + action increment/decrement/reset

@state {
  let count = prop({ default: 0 })

  const increment = action(() => { count++ })
  const decrement = action(() => { count-- })
  const reset = action(() => { count = 0 })
}

@template {
  <section class="counter">
    <output class="count">{count}</output>
    <div class="controls">
      <button on:click={decrement} class="btn">−</button>
      <button on:click={reset} class="btn btn-ghost">Reset</button>
      <button on:click={increment} class="btn">+</button>
    </div>
  </section>
}

@style {
  .counter { display: grid; gap: 0.75rem; padding: 1.5rem; max-width: 14rem; }
  .count { font-size: 2.5rem; font-variant-numeric: tabular-nums; text-align: center; display: block; }
  .controls { display: flex; gap: 0.5rem; }
  .btn { flex: 1; padding: 0.5rem; cursor: pointer; border: 1px solid var(--border, #ccc); border-radius: 4px; }
  .btn-ghost { background: transparent; }
}
`,
  },
  {
    id: 'aihu-modal',
    filename: 'aihu-modal.aihu',
    title: 'Modal',
    type: 'container',
    description:
      'Modal dialog — aria() declares role/aria-modal on the host, show toggles visibility, Escape and backdrop click dismiss.',
    constructs: ['prop', 'aria', 'action', 'show', 'slot', 'on:click', 'on:keydown'],
    packages: [],
    concerns: ['a11y', 'events', 'state'],
    since: '0.5.0',
    related: ['aihu-toast', 'aihu-accordion'],
    antiPatterns: [
      'Do not scatter role/aria-modal on inner wrappers — aria() declares them once on the host element.',
    ],
    source: `// modal — prop open, action show/hide, on:keydown for Escape, aria() for aria-modal+role="dialog"

@state {
  let open = prop({ default: false })

  aria({
    role: 'dialog',
    modal: 'true',
    label: 'Modal dialog',
  })

  const show = action(() => { open = true })
  const hide = action(() => { open = false })
  const onKeydown = action((e: KeyboardEvent) => {
      if (e.key === 'Escape') hide()
    })
}

@template {
  <div
    class="modal-root"
    show={open}
    on:keydown={onKeydown}
    tabindex="-1"
  >
    <div class="backdrop" on:click={hide}></div>
    <div class="modal-box" role="document">
      <button class="close-btn" on:click={hide} aria-label="Close dialog">×</button>
      <div class="modal-content">
        <slot />
      </div>
    </div>
  </div>
}

@style {
  .modal-root { position: fixed; inset: 0; z-index: 100; display: flex; align-items: center; justify-content: center; }
  .backdrop { position: absolute; inset: 0; background: rgba(0,0,0,0.5); }
  .modal-box { position: relative; background: var(--surface, #fff); border-radius: 8px; padding: 1.5rem; min-width: 20rem; max-width: 90vw; box-shadow: 0 8px 32px rgba(0,0,0,0.2); }
  .close-btn { position: absolute; top: 0.75rem; right: 0.75rem; background: none; border: none; font-size: 1.5rem; cursor: pointer; line-height: 1; color: var(--muted, #888); }
  .close-btn:hover { color: var(--fg, #111); }
  .modal-content { margin-top: 0.5rem; }
  [hidden] { display: none !important; }
}
`,
  },
  {
    id: 'aihu-tabs',
    filename: 'aihu-tabs.aihu',
    title: 'Tabs',
    type: 'container',
    description:
      'Tabs — derived() computes the selected tab, each/key renders the tablist, onMount picks the initial tab.',
    constructs: [
      'prop',
      'state',
      'derived',
      'action',
      'onMount',
      'each',
      'key',
      'if',
      'else',
      'group',
      'on:click',
      'interpolation',
    ],
    packages: [],
    concerns: ['state', 'a11y'],
    since: '0.5.0',
    playground: 'Tabs',
    related: ['aihu-accordion'],
    antiPatterns: [
      'Do not recompute the active tab inline in the template — derived() memoizes the selection once for every read site.',
    ],
    source: `// tabs — prop tabs + action selectTab, derived selected (active tab)

@state {
  const tabs = prop({
    default: [
        { id: 'overview', label: 'Overview', content: 'Overview panel content.' },
        { id: 'details', label: 'Details', content: 'Details panel content.' },
        { id: 'settings', label: 'Settings', content: 'Settings panel content.' },
      ],
  })

  let activeId = state('')

  const selected = derived(() => tabs.find(t => t.id === activeId) ?? tabs[0] ?? null)

  onMount(() => {
      if (tabs.length > 0) activeId = tabs[0].id
    })

  const selectTab = action((id: string) => { activeId = id })
}

@template {
  <div class="tabs-component">
    <div class="tab-list" role="tablist">
      <group each={tab of tabs} key={tab.id}>
        <button
          role="tab"
          class={['tab-btn', activeId === tab.id && 'active']}
          aria-selected={activeId === tab.id}
          on:click={() => selectTab(tab.id)}
        >
          {tab.label}
        </button>
      </group>
    </div>
    <div class="tab-panel" role="tabpanel">
      <group if={selected}>
        <p>{selected.content}</p>
      </group><group else>
        <p class="empty">No tab selected.</p>
      </group>
    </div>
  </div>
}

@style {
  .tabs-component { max-width: 32rem; border: 1px solid var(--border, #ccc); border-radius: 6px; overflow: hidden; }
  .tab-list { display: flex; border-bottom: 1px solid var(--border, #ccc); background: var(--tab-bar-bg, #f5f5f5); }
  .tab-btn { flex: 1; padding: 0.6rem 0.75rem; background: none; border: none; border-bottom: 3px solid transparent; cursor: pointer; font-size: 0.9rem; }
  .tab-btn.active { border-bottom-color: var(--accent, #0066cc); color: var(--accent, #0066cc); font-weight: 600; }
  .tab-panel { padding: 1rem; }
  .tab-panel p { margin: 0; }
  .empty { color: var(--muted, #888); font-style: italic; }
}
`,
  },
  {
    id: 'aihu-toast',
    filename: 'aihu-toast.aihu',
    title: 'Toast',
    type: 'container',
    description:
      'Toast — auto-dismiss via onMount setTimeout, manual dismiss action, aria-live polite status region.',
    constructs: [
      'prop',
      'state',
      'action',
      'onMount',
      'onDispose',
      'show',
      'on:click',
      'interpolation',
    ],
    packages: [],
    concerns: ['state', 'a11y'],
    since: '0.5.0',
    related: ['aihu-modal', 'aihu-clock'],
    antiPatterns: [
      'Do not auto-dismiss without clearing the timer in onDispose — a disposed toast must not fire a dangling timeout.',
    ],
    source: `// toast — prop message + action dismiss, auto-dismiss via onMount setTimeout

@state {
  const message = prop({ default: 'Something happened.' })
  const duration = prop({ default: 3000 })

  let visible = state(false)
  let _timerId: number | null = null

  const dismiss = action(() => {
      visible = false
      if (_timerId !== null) { clearTimeout(_timerId); _timerId = null }
    })

  onMount(() => {
      visible = true
      _timerId = setTimeout(() => { visible = false }, duration) as unknown as number
    })
  onDispose(() => {
      if (_timerId !== null) { clearTimeout(_timerId); _timerId = null }
    })
}

@template {
  <div
    class={['toast', visible && 'toast-visible']}
    role="status"
    aria-live="polite"
    show={visible}
  >
    <span class="toast-msg">{message}</span>
    <button class="toast-close" on:click={dismiss} aria-label="Dismiss">×</button>
  </div>
}

@style {
  .toast { display: flex; align-items: center; gap: 0.75rem; padding: 0.6rem 1rem; background: var(--toast-bg, #333); color: var(--toast-fg, #fff); border-radius: 6px; box-shadow: 0 4px 16px rgba(0,0,0,0.2); min-width: 16rem; max-width: 90vw; }
  .toast-msg { flex: 1; font-size: 0.9rem; }
  .toast-close { background: none; border: none; color: inherit; font-size: 1.2rem; cursor: pointer; opacity: 0.7; line-height: 1; padding: 0; }
  .toast-close:hover { opacity: 1; }
  [hidden] { display: none; }
}
`,
  },
  {
    id: 'aria-form',
    filename: 'aria-form.aihu',
    title: 'ARIA Form',
    type: 'form',
    description:
      'Form-associated element — aria() maps role/label/describedby, form() exposes value and validity to the surrounding form.',
    constructs: ['aria', 'state', 'form', 'action', 'bind:value', 'on:submit'],
    packages: [],
    concerns: ['a11y', 'state'],
    since: '0.5.0',
    related: ['form-validation'],
    antiPatterns: [
      'Do not mirror validity into ad-hoc CSS classes only — form() participates in real form submission and native :invalid styling.',
    ],
    source: `// aria-form — aria() for role/aria-label/aria-describedby, form() with value+validity

@state {
  aria({
    role: 'form',
    label: 'Contact form',
    describedby: 'aria-form-hint',
  })

  let name = state('')
  let email = state('')

  form({
    value: () => JSON.stringify({ name, email }),
    validity: () => ({ valueMissing: !name || !email }),
  })

  const onSubmit = action((e: Event) => {
      e.preventDefault()
      console.log('submitted', { name, email })
    })
}

@template {
  <form on:submit={onSubmit} class="aria-form">
    <p id="aria-form-hint" class="hint">All fields are required.</p>
    <label class="field">
      Name
      <input bind:value={name} placeholder="Your name" required />
    </label>
    <label class="field">
      Email
      <input type="email" bind:value={email} placeholder="you@example.com" required />
    </label>
    <button type="submit" class="submit-btn">Submit</button>
  </form>
}

@style {
  .aria-form { display: grid; gap: 0.75rem; max-width: 24rem; padding: 1.5rem; }
  .hint { font-size: 0.85rem; color: var(--muted, #666); margin: 0; }
  .field { display: flex; flex-direction: column; gap: 0.25rem; font-size: 0.9rem; font-weight: 500; }
  .field input { padding: 0.4rem 0.6rem; border: 1px solid var(--border, #ccc); border-radius: 4px; font-size: 1rem; }
  .submit-btn { padding: 0.5rem 1rem; background: var(--accent, #0066cc); color: white; border: none; border-radius: 4px; cursor: pointer; }
}
`,
  },
  {
    id: 'context-consumer',
    filename: 'context-consumer.aihu',
    title: 'Context Consumer',
    type: 'container',
    description:
      "consume() intrinsic — reads the 'theme' token provided by an ancestor context-provider.",
    constructs: ['consume', 'interpolation'],
    packages: [],
    concerns: ['state'],
    since: '0.5.0',
    related: ['context-provider', 'theme-toggle'],
    antiPatterns: [
      'Do not resolve context in module scope — consume() resolves against the ancestor chain at setup time, not import time.',
    ],
    source: `// context-consumer — consume(): reads theme from ancestor provider
// Pairs with context-provider.aihu; \`theme\` is the consumed provided value.

@state {
  const theme = consume<string>('theme')
}

@template {
  <div class={['consumer', theme]}>
    <p class="theme-label">
      Active theme: <strong>{theme}</strong>
    </p>
    <div class={['swatch', theme === 'dark' ? 'swatch-dark' : 'swatch-light']}></div>
  </div>
}

@style {
  .consumer { padding: 1rem; border-radius: 4px; transition: background 0.2s; }
  .consumer.light { background: #fff; color: #111; }
  .consumer.dark { background: #111; color: #f0f0f0; }
  .theme-label { margin: 0 0 0.5rem; font-size: 0.9rem; }
  .swatch { width: 2rem; height: 2rem; border-radius: 50%; border: 2px solid currentColor; }
  .swatch-light { background: #fff; }
  .swatch-dark { background: #111; }
}
`,
  },
  {
    id: 'context-provider',
    filename: 'context-provider.aihu',
    title: 'Context Provider',
    type: 'container',
    description:
      'provide() intrinsic — exposes a theme token to descendant consumers over the context prototype chain.',
    constructs: ['state', 'provide', 'action', 'slot', 'interpolation'],
    packages: [],
    concerns: ['state'],
    since: '0.5.0',
    related: ['context-consumer', 'theme-toggle'],
    antiPatterns: [
      'provide() must run during setup — do not call it inside onMount; descendants connecting during mount would miss the scope.',
    ],
    source: `// context-provider — provide(): exposes a theme token to descendants
// Pairs with context-consumer.aihu, which consumes 'theme' and renders it.

@state {
  let theme = state('light')

  provide('theme', theme)

  const setTheme = action((t: string) => { theme = t })
}

@template {
  <div class="provider" data-theme="light">
    <div class="controls">
      <span class="label">Providing theme: <strong>{theme}</strong></span>
    </div>
    <div class="slot-area">
      <slot />
    </div>
  </div>
}

@style {
  .provider { padding: 1rem; border: 2px solid var(--border, #ccc); border-radius: 6px; }
  .controls { display: flex; align-items: center; gap: 1rem; margin-bottom: 1rem; }
  .label { font-size: 0.9rem; color: var(--muted, #666); }
  .slot-area { padding-top: 0.5rem; border-top: 1px solid var(--border, #eee); }
}
`,
  },
  {
    id: 'data-table',
    filename: 'data-table.aihu',
    title: 'Data Table',
    type: 'list',
    description:
      'Sortable data table — derived() sorts a copy of the prop rows, each/key renders rows, click headers to toggle direction.',
    constructs: ['prop', 'state', 'derived', 'action', 'each', 'key', 'on:click', 'interpolation'],
    packages: [],
    concerns: ['state'],
    since: '0.5.0',
    related: ['infinite-scroll', 'search-debounce'],
    antiPatterns: [
      'Do not sort the prop array in place — [...rows].sort() keeps the source identity stable so the derivation re-runs cleanly.',
    ],
    source: `// data-table — prop rows + action sort(col), derived sortedRows, each with key

@state {
  const rows = prop({
    default: [
        { id: '1', name: 'Alice', role: 'Engineer', score: 92 },
        { id: '2', name: 'Bob', role: 'Designer', score: 78 },
        { id: '3', name: 'Carol', role: 'Manager', score: 85 },
        { id: '4', name: 'Dave', role: 'Engineer', score: 91 },
      ],
  })

  let sortCol = state('name')
  let sortDir = state(1)

  const sortedRows = derived(() => [...rows].sort((a, b) => {
      const av = String(a[sortCol] ?? '')
      const bv = String(b[sortCol] ?? '')
      return av.localeCompare(bv) * sortDir
    }))

  const sort = action((col: string) => {
      if (sortCol === col) {
        sortDir = sortDir === 1 ? -1 : 1
      } else {
        sortCol = col
        sortDir = 1
      }
    })
}

@template {
  <div class="data-table-wrapper">
    <table class="data-table">
      <thead>
        <tr>
          <th on:click={() => sort('name')} class={['col-hdr', sortCol === 'name' && 'sorted']}>Name {sortCol === 'name' ? (sortDir === 1 ? '▲' : '▼') : ''}</th>
          <th on:click={() => sort('role')} class={['col-hdr', sortCol === 'role' && 'sorted']}>Role {sortCol === 'role' ? (sortDir === 1 ? '▲' : '▼') : ''}</th>
          <th on:click={() => sort('score')} class={['col-hdr', sortCol === 'score' && 'sorted']}>Score {sortCol === 'score' ? (sortDir === 1 ? '▲' : '▼') : ''}</th>
        </tr>
      </thead>
      <tbody>
        <tr each={row of sortedRows} key={row.id} class="data-row">
          <td>{row.name}</td>
          <td>{row.role}</td>
          <td class="score">{row.score}</td>
        </tr>
      </tbody>
    </table>
  </div>
}

@style {
  .data-table-wrapper { overflow-x: auto; max-width: 100%; }
  .data-table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  .col-hdr { padding: 0.5rem 0.75rem; text-align: left; background: var(--table-hdr, #f5f5f5); border-bottom: 2px solid var(--border, #ccc); cursor: pointer; user-select: none; white-space: nowrap; }
  .col-hdr.sorted { color: var(--accent, #0066cc); }
  .data-row td { padding: 0.4rem 0.75rem; border-bottom: 1px solid var(--border, #eee); }
  .data-row:hover td { background: var(--hover-bg, #fafafa); }
  .score { font-variant-numeric: tabular-nums; font-weight: 600; }
}
`,
  },
  {
    id: 'fetch-resource',
    filename: 'fetch-resource.aihu',
    title: 'Fetch Resource',
    type: 'async',
    description:
      'resource() intrinsic — async fetch with loading/error/value states rendered through an if/elseif/else chain.',
    constructs: ['prop', 'resource', 'group', 'if', 'elseif', 'else', 'interpolation'],
    packages: [],
    concerns: ['state'],
    since: '0.5.0',
    related: ['agent-weather', 'search-debounce'],
    antiPatterns: [
      'Do not hand-roll loading/error state() flags around fetch inside an effect — resource() owns the loading/error/value lifecycle.',
    ],
    source: `// fetch-resource — resource() for async fetch with loading/error/data states

@state {
  const url = prop({ default: '/api/resource' })

  const data = resource(async () => {
      const res = await fetch(url)
      if (!res.ok) throw new Error(\`HTTP \${res.status}\`)
      return res.json()
    })
}

@template {
  <div class="fetch-resource">
    <group if={data.loading}>
      <p class="loading">Loading…</p>
    </group><group elseif={data.error}>
      <p class="error">Error: {data.error.message}</p>
    </group><group else>
      <pre class="result">{JSON.stringify(data.value, null, 2)}</pre>
    </group>
  </div>
}

@style {
  .fetch-resource { font-family: monospace; padding: 1rem; }
  .loading { color: var(--info, #036); }
  .error { color: var(--error, #c00); }
  .result { background: var(--code-bg, #f5f5f5); padding: 1rem; border-radius: 4px; overflow: auto; }
}
`,
  },
  {
    id: 'form-validation',
    filename: 'form-validation.aihu',
    title: 'Form Validation',
    type: 'form',
    description:
      'Live validation — form() exposes value/validity, derived() computes the error message, touched gates when errors show.',
    constructs: [
      'state',
      'form',
      'derived',
      'action',
      'if',
      'group',
      'on:input',
      'on:blur',
      'interpolation',
    ],
    packages: [],
    concerns: ['state', 'a11y'],
    since: '0.5.0',
    playground: 'Form',
    related: ['aria-form'],
    antiPatterns: [
      'Do not surface errors on every keystroke before first interaction — track touched so messages appear only after blur or input.',
    ],
    source: `// form-validation — form() with value+validity for form-associated custom element

@state {
  let value = state('')
  let touched = state(false)

  form({
    value: () => value,
    validity: () => ({ valueMissing: !value.trim(), tooShort: value.trim().length < 2 }),
  })

  const errorMessage = derived(() => {
      if (!touched) return ''
      if (!value.trim()) return 'This field is required.'
      if (value.trim().length < 2) return 'Must be at least 2 characters.'
      return ''
    })
  const isValid = derived(() => value.trim().length >= 2)

  const onInput = action((e: Event) => {
      value = (e.target as HTMLInputElement).value
      touched = true
    })
  const onBlur = action(() => { touched = true })
}

@template {
  <label class="form-field">
    <span class="field-label">Name <span aria-hidden="true">*</span></span>
    <input
      type="text"
      class={['field-input', touched && !isValid && 'invalid']}
      value={value}
      on:input={onInput}
      on:blur={onBlur}
      required
      minlength="2"
    />
    <group if={errorMessage}>
      <span class="error-msg" role="alert">{errorMessage}</span>
    </group>
    <group if={isValid}>
      <span class="valid-msg">Looks good!</span>
    </group>
  </label>
}

@style {
  .form-field { display: flex; flex-direction: column; gap: 0.3rem; max-width: 20rem; }
  .field-label { font-size: 0.9rem; font-weight: 600; }
  .field-input { padding: 0.5rem; border: 1px solid var(--border, #ccc); border-radius: 4px; font-size: 1rem; }
  .field-input.invalid { border-color: var(--error, #c00); }
  .error-msg { font-size: 0.8rem; color: var(--error, #c00); }
  .valid-msg { font-size: 0.8rem; color: var(--success, #080); }
}
`,
  },
  {
    id: 'guard-ui',
    filename: 'guard-ui.aihu',
    title: 'Guard UI',
    type: 'agent',
    description:
      "<guard> element — scope-gated UI that renders its children only when the 'admin' scope is verified.",
    constructs: ['guard', 'interpolation'],
    packages: [],
    concerns: ['governance'],
    since: '0.5.0',
    related: ['agent-weather'],
    antiPatterns: [
      'Do not treat <guard> as the security boundary — the server must enforce the same scope; the template guard is UX, not authorization.',
    ],
    source: `// guard-ui — <guard> scope-gated UI: shows content only when scope 'admin' verified

@state {
  const label: string = 'admin-only content'
}

@template {
  <div class="guard-wrapper">
    <guard scope="admin">
      <section class="admin-panel">
        <h2>Admin Panel</h2>
        <p>This {label} is only visible to users with the "admin" scope.</p>
        <button class="action-btn">Perform admin action</button>
      </section>
    </guard>
    <p class="fallback-note">
      Content outside the guard is always visible.
    </p>
  </div>
}

@style {
  .guard-wrapper { padding: 1rem; }
  .admin-panel { padding: 1rem; background: var(--admin-bg, #fff3cd); border: 1px solid var(--admin-border, #ffc107); border-radius: 4px; margin-bottom: 0.75rem; }
  .admin-panel h2 { margin: 0 0 0.5rem; font-size: 1.1rem; }
  .action-btn { margin-top: 0.5rem; padding: 0.4rem 0.75rem; cursor: pointer; border: 1px solid var(--border, #ccc); border-radius: 4px; }
  .fallback-note { font-size: 0.85rem; color: var(--muted, #666); }
}
`,
  },
  {
    id: 'infinite-scroll',
    filename: 'infinite-scroll.aihu',
    title: 'Infinite Scroll',
    type: 'list',
    description:
      'Infinite scroll — controller() wires an IntersectionObserver sentinel that calls the loadMore action; each/key/empty renders the list.',
    constructs: [
      'prop',
      'state',
      'action',
      'controller',
      'onMount',
      'each',
      'key',
      'empty',
      'group',
      'if',
      'interpolation',
    ],
    packages: [],
    concerns: ['state', 'events'],
    since: '0.5.0',
    related: ['data-table', 'aihu-controller'],
    antiPatterns: [
      'Do not fire loadMore from the observer without checking loading — re-entrant calls double-append pages.',
    ],
    source: `// infinite-scroll — prop page + action loadMore, IntersectionObserver via controller()

@state {
  const page = prop({ default: 1 })

  let loading = state(false)
  let items = state<Array<{ id: number; text: string }>>([])

  const loadMore = action(async () => {
    if (loading) return
    loading = true
    await new Promise(resolve => setTimeout(resolve, 400))
    const start = items.length
    items = [
      ...items,
      ...Array.from({ length: 10 }, (_, i) => ({
        id: start + i + 1,
        text: \`Item \${start + i + 1}\`,
      })),
    ]
    loading = false
  })

  const sentinel = controller(() => {
    let observer: IntersectionObserver | null = null
    return {
      hostConnected: () => {
        const el = (ctx.host as ShadowRoot).querySelector('.scroll-sentinel')
        if (!el) return
        observer = new IntersectionObserver((entries) => {
          if (entries[0]?.isIntersecting && !loading) {
            loadMore()
          }
        }, { threshold: 0.1 })
        observer.observe(el)
      },
      hostDisconnected: () => {
        observer?.disconnect()
        observer = null
      },
    }
  })

  onMount(() => { loadMore() })
}

@template {
  <div class="infinite-scroll">
    <ul class="item-list">
      <group each={item of items} key={item.id}>
        <li class="scroll-item">{item.text}</li>
      </group><group empty>
        <li class="scroll-item empty">Loading initial items…</li>
      </group>
    </ul>
    <group if={loading}>
      <p class="loading-indicator">Loading more…</p>
    </group>
    <div class="scroll-sentinel" aria-hidden="true"></div>
  </div>
}

@style {
  .infinite-scroll { max-width: 24rem; max-height: 400px; overflow-y: auto; border: 1px solid var(--border, #ccc); border-radius: 6px; }
  .item-list { list-style: none; padding: 0; margin: 0; }
  .scroll-item { padding: 0.6rem 0.75rem; border-bottom: 1px solid var(--border, #eee); font-size: 0.9rem; }
  .scroll-item:last-child { border-bottom: none; }
  .scroll-item.empty { color: var(--muted, #888); font-style: italic; }
  .loading-indicator { padding: 0.5rem 0.75rem; font-size: 0.85rem; color: var(--muted, #888); text-align: center; }
  .scroll-sentinel { height: 1px; }
}
`,
  },
  {
    id: 'search-debounce',
    filename: 'search-debounce.aihu',
    title: 'Search Debounce',
    type: 'list',
    description:
      'Debounced search — bind:value feeds the query, effect() debounces 300ms into a second state, derived() filters results.',
    constructs: [
      'state',
      'effect',
      'derived',
      'bind:value',
      'each',
      'key',
      'if',
      'elseif',
      'group',
      'interpolation',
    ],
    packages: [],
    concerns: ['state', 'events'],
    since: '0.5.0',
    playground: 'Search',
    related: ['data-table', 'fetch-resource'],
    antiPatterns: [
      'Do not debounce inside derived() — derivations must be pure; the timer lives in effect(), the settled value in its own state.',
    ],
    source: `// search-debounce — bind:value on input + effect() with 300ms debounce, derived results

@state {
  let query = state('')
  let debouncedQuery = state('')
  let _debounceTimer: number | null = null

  effect(() => {
    if (_debounceTimer !== null) clearTimeout(_debounceTimer)
    _debounceTimer = setTimeout(() => {
      debouncedQuery = query
      _debounceTimer = null
    }, 300) as unknown as number
  })

  const results = derived(() => {
      if (!debouncedQuery.trim()) return []
      const q = debouncedQuery.toLowerCase()
      return [
        'apple', 'apricot', 'banana', 'blueberry', 'cherry',
        'grape', 'kiwi', 'lemon', 'mango', 'orange', 'peach', 'pear',
      ].filter(item => item.includes(q))
    })
}

@template {
  <div class="search-box">
    <label class="search-label">
      Search fruits
      <input
        type="search"
        class="search-input"
        bind:value={query}
        placeholder="Type to search…"
        aria-label="Search fruits"
      />
    </label>
    <group if={query && results.length === 0}>
      <p class="no-results">No results for "<strong>{query}</strong>"</p>
    </group><group elseif={results.length > 0}>
      <ul class="result-list">
        <group each={item of results} key={item}>
          <li class="result-item">{item}</li>
        </group>
      </ul>
    </group>
  </div>
}

@style {
  .search-box { max-width: 22rem; padding: 1rem; }
  .search-label { display: flex; flex-direction: column; gap: 0.4rem; font-size: 0.9rem; font-weight: 500; }
  .search-input { padding: 0.5rem; border: 1px solid var(--border, #ccc); border-radius: 4px; font-size: 1rem; width: 100%; }
  .no-results { color: var(--muted, #888); font-size: 0.9rem; margin-top: 0.5rem; }
  .result-list { list-style: none; padding: 0; margin: 0.5rem 0 0; border: 1px solid var(--border, #ccc); border-radius: 4px; overflow: hidden; }
  .result-item { padding: 0.4rem 0.75rem; border-bottom: 1px solid var(--border, #eee); font-size: 0.9rem; }
  .result-item:last-child { border-bottom: none; }
}
`,
  },
  {
    id: 'ssr-hydration',
    filename: 'ssr-hydration.aihu',
    title: 'SSR Hydration',
    type: 'ssr-ssg',
    description:
      'SSR-safe bootstrapping — props render placeholders on the server; onMount reads server-stamped dataset values after hydration.',
    constructs: ['prop', 'state', 'onMount', 'interpolation'],
    packages: [],
    concerns: ['state', 'serialization'],
    since: '0.5.0',
    related: ['context-provider'],
    antiPatterns: [
      'Do not touch the DOM or dataset during setup — SSR executes setup on the server; DOM reads belong in onMount.',
    ],
    source: `// ssr-hydration — SSR-safe component: onMount hydrates from dataset

@state {
  let greeting = prop({ default: 'Hello' })
  let name = prop({ default: 'World' })

  let hydratedFrom: string = 'client'

  onMount(() => {
      const el = _host as HTMLElement
      if (el.dataset.ssrGreeting) greeting = el.dataset.ssrGreeting
      if (el.dataset.ssrName) name = el.dataset.ssrName
      hydratedFrom = el.dataset.ssrGreeting ? 'server' : 'client'
    })
}

@template {
  <div class="ssr-component">
    <p class="greeting">{greeting}, {name}!</p>
    <p class="hydration-source">
      Hydrated from: <code>{hydratedFrom}</code>
    </p>
  </div>
}

@style {
  .ssr-component { padding: 1rem; border: 1px solid var(--border, #ccc); border-radius: 4px; max-width: 24rem; }
  .greeting { font-size: 1.2rem; margin: 0 0 0.5rem; }
  .hydration-source { font-size: 0.8rem; color: var(--muted, #666); margin: 0; }
  code { background: var(--code-bg, #f5f5f5); padding: 0.1em 0.4em; border-radius: 3px; }
}
`,
  },
  {
    id: 'tailwind-style',
    filename: 'tailwind-style.aihu',
    title: 'Tailwind Style',
    type: 'display',
    description:
      'Tailwind utilities in the template coexisting with a scoped @style block for component-specific rules.',
    constructs: ['state', 'action', 'on:click', 'interpolation'],
    packages: [],
    concerns: ['styling', 'state'],
    since: '0.5.0',
    related: ['theme-toggle'],
    antiPatterns: [
      'Do not duplicate utility rules inside @style — the scoped block is for rules the utility layer cannot express.',
    ],
    source: `// tailwind-style — Tailwind 4 utility classes in template + scoped @style for component rules

@state {
  let active = state(false)
  let count = state(0)

  const toggle = action(() => { active = !active })
  const increment = action(() => { count++ })
}

@template {
  <div class="tw-card">
    <h2 class="text-xl font-semibold mb-4">Tailwind + Scoped Style</h2>
    <div class="flex gap-3 mb-4">
      <button
        class={['px-4 py-2 rounded font-medium transition-colors', active ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-700']}
        on:click={toggle}
      >
        {active ? 'Active' : 'Inactive'}
      </button>
      <button
        class="px-4 py-2 rounded font-medium bg-green-600 text-white hover:bg-green-700"
        on:click={increment}
      >
        Count: {count}
      </button>
    </div>
    <p class="status-label">
      Component-scoped style below the Tailwind layer.
    </p>
  </div>
}

@style {
  /* Component-specific rules that complement Tailwind utilities */
  .tw-card {
    padding: 1.5rem;
    border: 1px solid var(--border, #e5e7eb);
    border-radius: 0.5rem;
    max-width: 28rem;
  }
  .status-label {
    font-size: 0.8rem;
    color: var(--muted, #6b7280);
    border-top: 1px dashed var(--border, #e5e7eb);
    padding-top: 0.5rem;
    margin-top: 0.5rem;
  }
}
`,
  },
  {
    id: 'theme-toggle',
    filename: 'theme-toggle.aihu',
    title: 'Theme Toggle',
    type: 'display',
    description:
      'Theme switcher — state-backed theme is provided to descendants and mirrored onto documentElement by an effect.',
    constructs: ['state', 'provide', 'effect', 'action', 'on:click', 'interpolation'],
    packages: [],
    concerns: ['styling', 'state'],
    since: '0.5.0',
    playground: 'Theme',
    related: ['context-provider', 'tailwind-style'],
    antiPatterns: [
      'Do not toggle document-level classes inside action bodies — the effect() re-runs whenever theme changes, keeping DOM and state in sync from one place.',
    ],
    source: `// theme-toggle — dark/light toggle: provide() for theme + effect() for documentElement class

@state {
  let theme = state('light')

  provide('theme', theme)

  effect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark')
    document.documentElement.classList.toggle('light', theme === 'light')
  })

  const toggle = action(() => { theme = theme === 'light' ? 'dark' : 'light' })
  const setTheme = action((t: 'light' | 'dark') => { theme = t })
}

@template {
  <div class="theme-toggle">
    <button
      class={['toggle-btn', theme]}
      on:click={toggle}
      aria-label={\`Switch to \${theme === 'light' ? 'dark' : 'light'} theme\`}
    >
      {theme === 'light' ? '☀ Light' : '☾ Dark'}
    </button>
    <span class="current">Current: {theme}</span>
  </div>
}

@style {
  .theme-toggle { display: flex; align-items: center; gap: 1rem; padding: 0.75rem 1rem; }
  .toggle-btn { padding: 0.4rem 0.9rem; border: 1px solid var(--border, #ccc); border-radius: 20px; cursor: pointer; font-size: 0.9rem; transition: background 0.2s; }
  .toggle-btn.light { background: #fff; color: #333; }
  .toggle-btn.dark { background: #111; color: #eee; border-color: #555; }
  .current { font-size: 0.8rem; color: var(--muted, #888); }
}
`,
  },
]

export const GOVERNED: readonly Governed[] = [
  {
    id: 'G1',
    example: 'todo-mvc',
    subsystem: 'Core reactivity + template grammar',
    sources: ['todo-mvc.aihu'],
    exercises: [
      'state',
      'derived',
      'action',
      'effect',
      'onMount',
      'each',
      'key',
      'empty',
      'if',
      'show',
      'ref',
      'interpolation',
      'bind:value',
      'on:click',
      'on:change',
      'on:submit.prevent',
      'derived.expose',
      'action.expose',
      'expose:read',
      'expose:read-write',
      'describe',
      'localStorage',
    ],
    ci: 'build',
  },
  {
    id: 'G2',
    example: 'hacker-news',
    subsystem: 'SSR meta-framework',
    sources: [
      'src/pages/index.aihu',
      'src/pages/index.loader.ts',
      'src/pages/item/[id].aihu',
      'src/pages/item/[id].loader.ts',
      'src/pages/user/[id].aihu',
      'src/components/hn-comment.aihu',
    ],
    exercises: [
      'prop',
      'action',
      'route',
      'route.dynamic',
      'defineLoader',
      'ssr-hydration',
      'each',
      'key',
      'if',
      'html',
      'interpolation',
      'a-enhanced',
      'prefetch',
      'afterNavigate',
      'prop.expose',
      'expose:read',
      'describe',
    ],
    ci: 'compile+smoke',
  },
  {
    id: 'G3',
    example: 'layouts',
    subsystem: 'Router / layouts / navigation',
    sources: [
      'src/pages/index.aihu',
      'src/pages/dashboard.aihu',
      'src/layouts/app.aihu',
      'src/layouts/compact.aihu',
    ],
    exercises: ['route', 'route.head', 'route.layout', 'outlet', 'a-enhanced'],
    ci: 'build',
  },
  {
    id: 'G4',
    example: 'storefront',
    subsystem: 'Data + app-state platform',
    sources: [
      'src/storefront-root.aihu',
      'src/product-list.aihu',
      'src/cart-drawer.aihu',
      'src/cart-context.ts',
      'server.ts',
    ],
    exercises: [
      'state',
      'derived',
      'action',
      'provide',
      'if',
      'each',
      'key',
      'on:click',
      'interpolation',
      'expose:read',
      'expose:read-write',
      'describe',
      'requireAuth',
      'pkg:context',
      'pkg:auth',
    ],
    ci: 'compile+smoke',
  },
  {
    id: 'G5',
    example: 'realtime-scores',
    subsystem: 'Streaming / realtime',
    sources: ['src/realtime-scores.aihu'],
    exercises: [
      'state',
      'onMount',
      'onDispose',
      'websocket',
      'each',
      'key',
      'if',
      'interpolation',
      'class:directive',
    ],
    ci: 'compile+smoke',
  },
  {
    id: 'G6',
    example: 'css-engine-utility',
    subsystem: 'Styling system',
    sources: ['src/pages/index.aihu', 'vite.config.ts'],
    exercises: ['route', 'css-utility-fold', 'css-container-query', 'pkg:css-engine'],
    ci: 'build',
  },
  {
    id: 'G7',
    example: 'agent-driven-demo',
    subsystem: 'Agent surface / GX governance',
    sources: ['src/task-list.aihu'],
    exercises: [
      'state',
      'action',
      'each',
      'key',
      'interpolation',
      'action.expose',
      'expose:read',
      'describe',
      'agent-block',
    ],
    ci: 'compile+smoke',
  },
  {
    id: 'G8',
    example: 'ssg-site',
    subsystem: 'SSG / static output',
    sources: [
      'aihu.config.ts',
      'src/pages/index.aihu',
      'src/pages/about.aihu',
      'src/components/theme-badge.aihu',
    ],
    exercises: [
      'output:static',
      'route',
      'route.head',
      'each',
      'key',
      'interpolation',
      'a-enhanced',
      'prop',
      'prop.attribute',
      'prop.reflect',
      'prop.expose',
      'expose:read',
      'describe',
      'state',
      'onAdopt',
      'onAttributeChange',
      'slot',
      'ssr-hydration',
    ],
    ci: 'build',
  },
  {
    id: 'G9',
    example: 'agent-hub',
    subsystem: 'Agent protocols (A2A + ACP)',
    sources: [
      'src/hub-root.aihu',
      'src/a2a-panel.aihu',
      'src/acp-panel.aihu',
      'src/hub-context.ts',
      'server.ts',
    ],
    exercises: [
      'state',
      'derived',
      'action',
      'provide',
      'if',
      'each',
      'key',
      'on:click',
      'interpolation',
      'expose:read',
      'describe',
      'pkg:context',
      'pkg:agent-a2a',
      'pkg:agent-acp',
    ],
    ci: 'compile+smoke',
  },
]

/** id → recipe, for the per-recipe detail pages + the playground seed lookup. */
export const RECIPE_BY_ID: Readonly<Record<string, Recipe>> = Object.fromEntries(
  COOKBOOK.map((r) => [r.id, r]),
)

/** The recipes wired into the in-browser WASM playground, in corpus order. */
export const PLAYGROUND_PRESETS: readonly Recipe[] = COOKBOOK.filter((r) => !!r.playground)

/**
 * Source shown in the landing hero. Kept as a literal (not inline in the page's
 * @state) because the aihu SSR-eligibility scanner reads reactive-looking tokens
 * (`prop(`, `action(`, `on:click`) literally — inlining aihu source in a page's
 * @state would misclassify the page as interactive and drop it from the DOM-free
 * prerender path.
 */
export const HERO_SOURCE = `@state {
  // one declaration — reactive for humans, discoverable for agents
  let city = prop({
    default: 'London',
    describe: 'City to forecast',
    expose: 'read write',
  })

  const refresh = action(
    { describe: 'Fetch the latest forecast', expose: 'read write' },
    async () => { forecast = await getForecast(city) },
  )
}

@template {
  <button on:click={refresh}>Forecast {city}</button>
}`

/**
 * The AGENT SURFACE half of the dual-surface card — the exposed expose/describe
 * contract an agent discovers for weather.aihu over MCP / A2A. Mirrors the
 * `expose` declarations in HERO_SOURCE so the two projections are provably one
 * component.
 */
export interface AgentSurfaceEntry {
  readonly kind: 'prop' | 'action'
  readonly name: string
  readonly describe: string
  readonly expose: string
}
export const AGENT_SURFACE: readonly AgentSurfaceEntry[] = [
  { kind: 'prop', name: 'city', describe: 'City to forecast', expose: 'read write' },
  { kind: 'action', name: 'refresh', describe: 'Fetch the latest forecast', expose: 'read write' },
]

/** Source for the live counter shown in the examples playground (the corpus recipe). */
export const COUNTER_SOURCE: string = RECIPE_BY_ID['aihu-counter']?.source ?? ''

/**
 * Recipes with a REAL hydrated island already registered in `main.ts` — the
 * "Run" affordance shows the live custom element for these. Every other recipe
 * is source-only until the in-browser WASM playground lands (deferred; see the
 * follow-up note in the docs app's cookbook build). Hand-authored, not corpus data.
 */
export const LIVE_ISLANDS: Readonly<Record<string, { tag: string; attrs: string }>> = {
  'aihu-counter': { tag: 'counter-demo', attrs: 'count="0"' },
  'agent-weather': { tag: 'weather-demo', attrs: 'city="London"' },
}
