export type { Dispose, EffectFn } from './effect.ts'
export { effect } from './effect.ts'
export { SignalCircularError, SignalError } from './errors.ts'
export type { Read, Signal, SignalOptions, Write } from './signal.ts'
export { signal } from './signal.ts'
