// AUTO-GENERATED by scripts/gen-cn-conflict-map.ts — DO NOT EDIT.
// Source of truth: aihu-css-core `tokens::conflict_groups()` (the utility
// registry). Regenerate with `bun run gen:cn-map`. Hand-edits will be lost.
//
// Maps a utility class PREFIX to the CSS property group it controls. Two
// classes conflict (last wins) when they resolve to the same group.

/** Prefix → conflict-group key, sorted longest-prefix-first. */
export const CONFLICT_GROUPS: Record<string, string> = {
  'outline': 'outline-color',
  'opacity': 'opacity',
  'rounded': 'border-radius',
  'border': 'border-color',
  'stroke': 'stroke',
  'shadow': 'box-shadow',
  'gap-x': 'column-gap',
  'gap-y': 'row-gap',
  'min-w': 'min-width',
  'max-w': 'max-width',
  'min-h': 'min-height',
  'max-h': 'max-height',
  'text': 'color',
  'fill': 'fill',
  'ring': '--tw-ring-color',
  'font': 'font-weight',
  'gap': 'gap',
  'px': 'padding-inline',
  'py': 'padding-block',
  'pt': 'padding-top',
  'pr': 'padding-right',
  'pb': 'padding-bottom',
  'pl': 'padding-left',
  'mx': 'margin-inline',
  'my': 'margin-block',
  'mt': 'margin-top',
  'mr': 'margin-right',
  'mb': 'margin-bottom',
  'ml': 'margin-left',
  'bg': 'background-color',
  'p': 'padding',
  'm': 'margin',
  'w': 'width',
  'h': 'height',
  'z': 'z-index',
}
