//! Globs `recipes/*.css` (D4 §6, Slice 4 — the daisyUI-style recipe channel)
//! into a generated `RECIPE_SOURCES: &[&str]` constant, so dropping in a new
//! recipe family file (`recipes/toggle.css`) needs no Rust-source edit —
//! `src/recipes.rs` just iterates whatever this discovers.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let recipes_dir = Path::new(&manifest_dir).join("recipes");
    println!("cargo:rerun-if-changed={}", recipes_dir.display());

    let mut entries: Vec<_> = fs::read_dir(&recipes_dir)
        .unwrap_or_else(|e| {
            panic!(
                "recipes/ directory must exist at {}: {e}",
                recipes_dir.display()
            )
        })
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("css"))
        .collect();
    entries.sort();

    let mut code = String::from(
        "/// Generated by build.rs from `recipes/*.css` — see `src/recipes.rs`.\n\
         pub static RECIPE_SOURCES: &[&str] = &[\n",
    );
    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let path_str = path.to_str().expect("recipe path must be valid UTF-8");
        code.push_str(&format!("    include_str!({path_str:?}),\n"));
    }
    code.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let dest = Path::new(&out_dir).join("recipes_generated.rs");
    fs::write(&dest, code).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
