/**
 * Full docs-site build script.
 *
 * Steps:
 *   0. Fetch the latest aihu-compile-wasm.tar.gz from GitHub Releases
 *      and extract it to `dist/wasm/` (Directive 1 — homepage
 *      playground). Skipped silently if no release is available.
 *   1. Read every `docs/site/*.md` from the repo root
 *   2. Render Markdown → HTML with `marked`
 *   3. Write `src/content.ts` with a `window.__DOCS__` map
 *   4. Run `rolldown -c rolldown.config.ts` to bundle the aihu components
 *
 * Usage:
 *   bun run build.ts
 */

import { execFileSync } from 'node:child_process'
import { copyFile, readdir, readFile, writeFile } from 'node:fs/promises'
import { basename, extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { marked } from 'marked'

const __dir = fileURLToPath(new URL('.', import.meta.url))
const docsDir = join(__dir, '../../docs/site')
const contentOut = join(__dir, 'src/content.ts')
const wasmFetcher = join(__dir, '../../scripts/fetch-wasm-bundle.ts')
const wasmOutDir = join(__dir, 'dist/wasm')

// ── 0. Fetch the WASM playground bundle ──────────────────────────

console.log('Fetching WASM playground bundle…')
try {
  execFileSync(process.execPath, [wasmFetcher, wasmOutDir], {
    cwd: __dir,
    stdio: 'inherit',
  })
} catch (err) {
  // Soft-fail: prebuild prints its own diagnostics. Build continues
  // and the playground renders the runtime fallback.
  console.warn(`WASM bundle fetch failed: ${(err as Error).message}`)
}

// ── 1. Collect all .md files from docs/site/ ─────────────────────

const files = (await readdir(docsDir)).filter((f) => extname(f) === '.md').sort()

console.log(`Found ${files.length} Markdown files in docs/site/`)

// ── 2. Render each file ──────────────────────────────────────────

interface DocPage {
  id: string
  title: string
  html: string
}

const pages: DocPage[] = []

for (const file of files) {
  const id = basename(file, '.md')
  const source = await readFile(join(docsDir, file), 'utf8')
  const html = await marked.parse(source, { gfm: true, breaks: false })

  // Extract title from first H1
  const titleMatch = source.match(/^#\s+(.+)$/m)
  const title = titleMatch ? titleMatch[1].trim() : id

  // Escape template-literal special chars so the generated TS is valid
  const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${')
  pages.push({ id, title, html: escaped })
  console.log(`  ✓ ${file} → "${title}"`)
}

// ── 3. Write src/content.ts ──────────────────────────────────────

// Biome noQuotedObjectKeys: only quote keys that aren't valid identifiers
const jsIdent = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/
const entries = pages
  .map((p) => {
    const key = jsIdent.test(p.id) ? p.id : `'${p.id}'`
    return `  ${key}: {\n    title: '${p.title.replace(/'/g, "\\'")}',\n    html: \`${p.html}\`,\n  }`
  })
  .join(',\n')

const contentTs = `/**
 * Pre-rendered Markdown pages — generated by build.ts.
 * Do not edit directly; run \`bun run build\` to regenerate.
 */

declare global {
  interface Window {
    __DOCS__: Record<string, { title: string; html: string }>
  }
}

window.__DOCS__ = {
${entries}
}
`

await writeFile(contentOut, contentTs, 'utf8')
console.log(`\nWrote src/content.ts (${pages.length} pages)`)

// ── 4. Bundle with rolldown ──────────────────────────────────────

console.log('\nBundling with rolldown…')
// Use execFileSync with array args (no shell) to avoid injection risk
execFileSync(
  process.execPath, // bun
  ['x', 'rolldown', '-c', 'rolldown.config.ts'],
  { cwd: __dir, stdio: 'inherit' },
)
console.log('\n✓ Build complete → dist/')

// ── 5. Copy static assets into dist/ ────────────────────────────

// index.html references ./dist/docs.js at development time (so the dev
// server at apps/docs/ root can find the bundle). When deployed, dist/ IS
// the root, so rewrite the path to ./docs.js in the copied file.
const indexSrc = await readFile(join(__dir, 'index.html'), 'utf8')
const indexDist = indexSrc.replace('./dist/docs.js', './docs.js')
await writeFile(join(__dir, 'dist', 'index.html'), indexDist, 'utf8')

const staticFiles = ['style.css', 'favicon.svg', 'aihu-wordmark.svg']
for (const file of staticFiles) {
  await copyFile(join(__dir, file), join(__dir, 'dist', file))
}

// Copy public/ (_headers, _redirects, etc.)
const publicDir = join(__dir, 'public')
const publicFiles = await readdir(publicDir).catch(() => [])
for (const file of publicFiles) {
  await copyFile(join(publicDir, file), join(__dir, 'dist', file))
}

console.log('✓ Static assets copied → dist/')
