import { existsSync, readFileSync } from 'node:fs'
import { relative as relativePath, resolve as resolvePath } from 'node:path'
import type { AdapterContext, AihuAdapter, ServerEntryContext } from '@aihu/app'

/**
 * A single route as exposed on AdapterContext.routes. We derive the element
 * type from the context interface so the adapter never takes a direct
 * dependency on @aihu/router. The non-serializable `module()` function is
 * irrelevant at adapt() time and is dropped from the emitted manifest.
 */
type ContextRoute = AdapterContext['routes'][number]

export interface CloudflareAdapterOptions {
  /**
   * Cloudflare Worker name. Used in generated wrangler.toml.
   * Default: value of "name" in the project's package.json, or 'aihu-app'.
   */
  name?: string
  /**
   * Deployment mode.
   * - 'workers': Cloudflare Workers with static assets via env.ASSETS binding
   * - 'pages': Cloudflare Pages (_worker.js convention — same output, different deploy target)
   * Default: 'workers'
   */
  mode?: 'workers' | 'pages'
  /**
   * Whether to write wrangler.toml in the project root if it does not exist.
   * Never overwrites an existing wrangler.toml.
   * Default: true
   */
  generateWrangler?: boolean
  /**
   * Enable SSR + static hybrid mode.
   *
   * When true, the generated `_worker.js` calls your aihu server handler first
   * (SSR routes, API routes, agent-readiness endpoints), then falls back to
   * Cloudflare's ASSETS binding for pre-rendered static files, and finally
   * falls back to `/index.html` for client-side-routed SPA pages.
   *
   * Route priority: SSR handler → ASSETS (CDN edge) → /index.html (SPA shell)
   *
   * Default: false (SPA-only mode, all requests served from ASSETS)
   */
  ssr?: boolean
}

function readPackageJsonName(root: string): string | null {
  const pkgPath = resolvePath(root, 'package.json')
  if (!existsSync(pkgPath)) return null
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { name?: string }
    return typeof pkg.name === 'string' ? pkg.name : null
  } catch {
    return null
  }
}

function generateWorkerEntry(): string {
  return [
    '// AUTO-GENERATED by @aihu/adapter-cloudflare — do not edit',
    '// Cloudflare Workers entry — SPA mode',
    '//',
    '// All page requests are served from the ASSETS binding (Cloudflare CDN).',
    '// For SSR mode use: cloudflare({ ssr: true })',
    '',
    'export default {',
    '  async fetch(request, env, _ctx) {',
    '    try {',
    '      return await env.ASSETS.fetch(request)',
    '    } catch {',
    '      // Fallback to index.html for client-side routing (404 from ASSETS).',
    '      const url = new URL(request.url)',
    "      const indexUrl = new URL('/index.html', url.origin)",
    '      return env.ASSETS.fetch(new Request(indexUrl, request))',
    '    }',
    '  },',
    '}',
  ].join('\n')
}

function generateSsrWorkerEntry(handlerSource: string): string {
  return [
    '// AUTO-GENERATED by @aihu/adapter-cloudflare — do not edit',
    '// Cloudflare Workers entry — SSR + static hybrid',
    '//',
    '// Route priority:',
    '//   1. SSR handler  — your aihu routes (API, agent-readiness, server-rendered pages)',
    '//   2. ASSETS       — pre-rendered static files served from Cloudflare CDN',
    '//   3. /index.html  — SPA shell fallback for client-side-routed pages',
    '',
    handlerSource,
    '',
    'export default {',
    '  async fetch(request, env, _ctx) {',
    '    // SSR: try your server routes first',
    '    const response = await handler(request, { env })',
    '    if (response.status !== 404) return response',
    '',
    '    // Static: pre-rendered pages and assets from ASSETS binding',
    '    try {',
    '      return await env.ASSETS.fetch(request)',
    '    } catch {',
    '      // SPA shell fallback for client-side routing',
    '      const url = new URL(request.url)',
    "      return env.ASSETS.fetch(new Request(new URL('/index.html', url.origin), request))",
    '    }',
    '  },',
    '}',
  ].join('\n')
}

/**
 * The `output: 'ssr'` worker wrapper, contributed INTO
 * `virtual:aihu-server-entry` rather than written to disk after the build.
 *
 * That relocation is the whole fix. The `ssr: true` path below emits its worker
 * as a string at `closeBundle`, outside the module graph, where it cannot
 * import `virtual:aihu-routes` — so `generateRoutesManifest` gives every route
 * a 404 placeholder and the worker renders nothing. Here `handler` is a real
 * `createServerRouter` over real route chunks, with the SSR child registry
 * already resolved.
 *
 * Route priority is unchanged from `generateSsrWorkerEntry`: SSR handler →
 * ASSETS (CDN edge) → `/index.html` (SPA shell).
 *
 * `env`/`ctx` are accepted by the `fetch` signature but NOT threaded into
 * `handler` — `ServerRouter.handle` takes a `Request` and nothing else, so
 * Worker bindings are not reachable from a page render yet. Named here rather
 * than papered over with an ignored argument.
 */
function generateServerEntryWrapper({ handler }: ServerEntryContext): string {
  return [
    '// Cloudflare Workers wrapper — contributed by @aihu/adapter-cloudflare',
    '//   1. SSR handler  — real route modules, server-rendered',
    '//   2. ASSETS       — client bundle + static files from the Cloudflare CDN',
    '//   3. /index.html  — SPA shell fallback for client-side-routed pages',
    'export default {',
    '  async fetch(request, env, _ctx) {',
    `    const response = await ${handler}(request)`,
    '    if (response.status !== 404) return response',
    '    try {',
    '      return await env.ASSETS.fetch(request)',
    '    } catch {',
    '      const url = new URL(request.url)',
    "      return env.ASSETS.fetch(new Request(new URL('/index.html', url.origin), request))",
    '    }',
    '  },',
    '}',
  ].join('\n')
}

/**
 * Generate the source text of `routes-manifest.js`.
 *
 * @deprecated Superseded by `serverEntry` + `output: 'ssr'`. Kept so existing
 * `cloudflare({ ssr: true })` configs keep building; deletion is a follow-up.
 *
 * CORRECTION to what this docblock used to say. It blamed the 404 placeholders
 * on the page component living "behind a non-serializable `module()` thunk".
 * That is false, and it sent every prior fix attempt in the wrong direction:
 * `@aihu/app`'s `fileToRouteDefinition` builds
 * `module: () => Promise.resolve({ default: null })`, so there was never a
 * loadable module to serialize and no adapter-side fix was possible. Route
 * modules can only come from `virtual:aihu-routes`, from inside the build
 * graph — which is what `serverEntry` above does.
 *
 * The SSR worker's handler does `import routes from './routes-manifest.js'`
 * and then `createRequestRouter({ routes })`, so this module provides a default
 * export that is an array of route entries, each carrying a `pattern` and a
 * placeholder `handler` that 404s — letting the worker fall through to the
 * ASSETS binding (pre-rendered static pages).
 */
function generateRoutesManifest(routes: ReadonlyArray<ContextRoute>): string {
  const serialized = routes.map((route) => {
    const r = route as ContextRoute & { name?: string; ssr?: boolean }
    const entry: { pattern: string; segments: unknown; name?: string; ssr?: boolean } = {
      pattern: r.pattern,
      segments: r.segments,
    }
    if (typeof r.name === 'string') entry.name = r.name
    if (typeof r.ssr === 'boolean') entry.ssr = r.ssr
    return entry
  })

  return [
    '// AUTO-GENERATED by @aihu/adapter-cloudflare — do not edit',
    '// Routes manifest consumed by the SSR worker handler.',
    '//',
    '// `routes` is the default export and is wired into createRequestRouter via',
    '// `const _manifest = { routes }`. Each route carries a `pattern` (required',
    '// by the router) plus serialized metadata. The page component itself is not',
    '// serializable, so each route uses a placeholder handler that 404s, letting',
    '// the worker fall through to the ASSETS binding (pre-rendered static files).',
    '',
    'const notFound = () => new Response(null, { status: 404 })',
    '',
    `const routes = ${JSON.stringify(serialized, null, 2)}.map((route) => ({`,
    '  ...route,',
    '  handler: notFound,',
    '}))',
    '',
    'export default routes',
    '',
  ].join('\n')
}

/**
 * `main`/`[assets] directory` differ between the two shapes, and getting them
 * wrong is a security bug, not a config nit.
 *
 * Legacy (`ssr`/SPA string emission): `_worker.js` is written INTO the client
 * outDir, so `main` is relative to it and `directory = "."` is that same dir.
 *
 * `output: 'ssr'`: the server bundle lands in a SIBLING `dist-server/`, and the
 * assets directory stays the client `dist/`. Pointing `[assets] directory` at a
 * root containing SSR chunks would let Cloudflare's ASSETS binding serve server
 * code on a public URL (D-2). Written relative to the project root, since that
 * is where wrangler.toml lives.
 */
function generateWranglerToml(name: string, ssrOutput: boolean, clientOutDir: string): string {
  return `${[
    '# AUTO-GENERATED by @aihu/adapter-cloudflare',
    '# Edit this file to customize your Worker configuration.',
    '# Reference: https://developers.cloudflare.com/workers/wrangler/configuration/',
    '',
    `name = "${name}"`,
    ssrOutput ? 'main = "dist-server/_worker.js"' : 'main = "_worker.js"',
    'compatibility_date = "2024-01-01"',
    '',
    '[assets]',
    // Deliberately NOT the SSR outDir, and deliberately not a shared parent of
    // both: either would publish the server bundle.
    ssrOutput ? `directory = "${clientOutDir}"` : 'directory = "."',
    'binding = "ASSETS"',
  ].join('\n')}\n`
}

/**
 * Cloudflare Workers / Pages adapter for aihu.
 *
 * Writes `_worker.js` to the Vite output directory and optionally creates
 * `wrangler.toml` in the project root (if absent).
 *
 * @example
 * // aihu.config.ts
 * import { defineConfig } from '@aihu/app'
 * import { cloudflare } from '@aihu/adapter-cloudflare'
 *
 * export default defineConfig({
 *   adapter: cloudflare({ name: 'my-worker' }),
 * })
 */
export function cloudflare(options?: CloudflareAdapterOptions): AihuAdapter {
  return {
    name: 'cloudflare',

    serverEntry: generateServerEntryWrapper,

    async adapt(context: AdapterContext): Promise<void> {
      const workerName = options?.name ?? readPackageJsonName(context.root) ?? 'aihu-app'
      const ssrOutput = context.config.output === 'ssr'

      // `output: 'ssr'` owns the worker entirely: it IS
      // `virtual:aihu-server-entry`, already written by the ssr environment's
      // build to `dist-server/_worker.js`. Emitting a second `_worker.js` into
      // the client outDir here would shadow it with a static-only shell — and
      // that shell is what the ASSETS binding would serve. So the only thing
      // left to do is wrangler.toml.
      if (ssrOutput) {
        const wranglerPathSsr = resolvePath(context.root, 'wrangler.toml')
        if (options?.generateWrangler !== false && !existsSync(wranglerPathSsr)) {
          const rel = relativePath(context.root, context.outDir).replace(/\\/g, '/') || '.'
          await context.writeFile(wranglerPathSsr, generateWranglerToml(workerName, true, rel))
          console.log(
            `[@aihu/adapter-cloudflare] Created wrangler.toml (name = "${workerName}", ` +
              `main = dist-server/_worker.js, assets = ${rel})`,
          )
        }
        console.log(
          `[@aihu/adapter-cloudflare] output: 'ssr' — the worker is the build's own ` +
            `dist-server/_worker.js; no _worker.js emitted into ${context.outDir}`,
        )
        console.log(
          `[@aihu/adapter-cloudflare] Deploy with: wrangler deploy --config wrangler.toml`,
        )
        return
      }

      const ssrEnabled = options?.ssr === true

      // Default specifier the handler imports. Keep in sync with the file we
      // emit below so `import routes from '<spec>'` always resolves.
      const routesSpecifier = './routes-manifest.js'

      // Step 1 — In SSR mode, write routes-manifest.js BEFORE _worker.js.
      // The generated handler does `import routes from './routes-manifest.js'`,
      // so this file must exist for the worker to load.
      if (ssrEnabled) {
        const manifestRelPath = routesSpecifier.replace(/^\.\//, '')
        await context.emitFile(manifestRelPath, generateRoutesManifest(context.routes))
        console.log(
          `[@aihu/adapter-cloudflare] Wrote ${manifestRelPath} (${context.routes.length} route(s))`,
        )
      }

      // Step 2 — Write _worker.js
      const workerEntry = ssrEnabled
        ? generateSsrWorkerEntry(context.createHandlerSource({ routesSpecifier }))
        : generateWorkerEntry()
      await context.emitFile('_worker.js', workerEntry)
      console.log(
        `[@aihu/adapter-cloudflare] Wrote _worker.js (${ssrEnabled ? 'SSR hybrid' : 'SPA'} mode)`,
      )

      // Step 3 — Write wrangler.toml (only if absent, never overwrites)
      const wranglerPath = resolvePath(context.root, 'wrangler.toml')
      if (options?.generateWrangler !== false && !existsSync(wranglerPath)) {
        const toml = generateWranglerToml(workerName, false, '.')
        await context.writeFile(wranglerPath, toml)
        console.log(`[@aihu/adapter-cloudflare] Created wrangler.toml (name = "${workerName}")`)
      }

      console.log(`[@aihu/adapter-cloudflare] Build complete → ${context.outDir}`)
      console.log(`[@aihu/adapter-cloudflare] Deploy with: wrangler deploy --config wrangler.toml`)
    },
  }
}
