import { existsSync, readFileSync } from 'node:fs'
import { resolve as resolvePath } from 'node:path'
import type { AihuAdapter, AdapterContext } from '@aihu/app'

export interface CloudflareAdapterOptions {
  /**
   * Cloudflare Worker name. Used in generated wrangler.toml.
   * Default: value of "name" in the project's package.json, or 'aihu-app'.
   */
  name?: string
  /**
   * Deployment mode.
   * - 'workers': Cloudflare Workers with static assets via env.ASSETS binding
   * - 'pages': Cloudflare Pages (_worker.js convention — same output, different deploy target)
   * Default: 'workers'
   */
  mode?: 'workers' | 'pages'
  /**
   * Whether to write wrangler.toml in the project root if it does not exist.
   * Never overwrites an existing wrangler.toml.
   * Default: true
   */
  generateWrangler?: boolean
}

function readPackageJsonName(root: string): string | null {
  const pkgPath = resolvePath(root, 'package.json')
  if (!existsSync(pkgPath)) return null
  try {
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8')) as { name?: string }
    return typeof pkg.name === 'string' ? pkg.name : null
  } catch {
    return null
  }
}

function generateWorkerEntry(): string {
  return [
    '// AUTO-GENERATED by @aihu/adapter-cloudflare — do not edit',
    '// Cloudflare Workers entry — SPA mode',
    '//',
    '// All page requests are served from the ASSETS binding (Cloudflare CDN).',
    '// For SSR mode, upgrade to @aihu/adapter-cloudflare with ssr: true (V1+).',
    '',
    'export default {',
    '  async fetch(request, env, _ctx) {',
    '    try {',
    '      return await env.ASSETS.fetch(request)',
    '    } catch {',
    "      // Fallback to index.html for client-side routing (404 from ASSETS).",
    '      const url = new URL(request.url)',
    "      const indexUrl = new URL('/index.html', url.origin)",
    '      return env.ASSETS.fetch(new Request(indexUrl, request))',
    '    }',
    '  },',
    '}',
  ].join('\n')
}

function generateWranglerToml(name: string): string {
  return [
    '# AUTO-GENERATED by @aihu/adapter-cloudflare',
    '# Edit this file to customize your Worker configuration.',
    '# Reference: https://developers.cloudflare.com/workers/wrangler/configuration/',
    '',
    `name = "${name}"`,
    'main = "_worker.js"',
    'compatibility_date = "2024-01-01"',
    '',
    '[assets]',
    'directory = "."',
    'binding = "ASSETS"',
  ].join('\n') + '\n'
}

/**
 * Cloudflare Workers / Pages adapter for aihu.
 *
 * Writes `_worker.js` to the Vite output directory and optionally creates
 * `wrangler.toml` in the project root (if absent).
 *
 * @example
 * // aihu.config.ts
 * import { defineConfig } from '@aihu/app'
 * import { cloudflare } from '@aihu/adapter-cloudflare'
 *
 * export default defineConfig({
 *   adapter: cloudflare({ name: 'my-worker' }),
 * })
 */
export function cloudflare(options?: CloudflareAdapterOptions): AihuAdapter {
  return {
    name: 'cloudflare',

    async adapt(context: AdapterContext): Promise<void> {
      const workerName =
        options?.name ?? readPackageJsonName(context.root) ?? 'aihu-app'

      // Step 1 — Write _worker.js
      const workerEntry = generateWorkerEntry()
      await context.emitFile('_worker.js', workerEntry)
      console.log(`[@aihu/adapter-cloudflare] Wrote _worker.js (SPA mode)`)

      // Step 2 — Write wrangler.toml (only if absent, never overwrites)
      const wranglerPath = resolvePath(context.root, 'wrangler.toml')
      if (options?.generateWrangler !== false && !existsSync(wranglerPath)) {
        const toml = generateWranglerToml(workerName)
        await context.writeFile(wranglerPath, toml)
        console.log(
          `[@aihu/adapter-cloudflare] Created wrangler.toml (name = "${workerName}")`,
        )
      }

      console.log(
        `[@aihu/adapter-cloudflare] Build complete → ${context.outDir}`,
      )
      console.log(
        `[@aihu/adapter-cloudflare] Deploy with: wrangler deploy --config wrangler.toml`,
      )
    },
  }
}
