/**
 * Pre-rendered Markdown pages — generated by build.ts.
 * Do not edit directly; run `bun run build` to regenerate.
 */

declare global {
  interface Window {
    __DOCS__: Record<string, { title: string; html: string }>
  }
}

window.__DOCS__ = {
  'api-reference': {
    title: 'API Reference',
    html: `<h1>API Reference</h1>
<h2>@aihu/signals</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>signal&lt;T&gt;(initial)</code></td>
<td>Create a writable reactive cell</td>
</tr>
<tr>
<td><code>computed&lt;T&gt;(fn)</code></td>
<td>Derive a read-only signal from other signals</td>
</tr>
<tr>
<td><code>effect(fn)</code></td>
<td>Run a side-effect; auto-tracks signal reads; returns dispose</td>
</tr>
<tr>
<td><code>batch(fn)</code></td>
<td>Defer effect flushes until fn completes</td>
</tr>
<tr>
<td><code>untrack(fn)</code></td>
<td>Read signals inside fn without subscribing</td>
</tr>
<tr>
<td><code>latticeSignal&lt;T&gt;(merge, initial)</code></td>
<td>Merge-monotone signal</td>
</tr>
<tr>
<td><code>boolLatticeSignal(initial?)</code></td>
<td>Boolean lattice signal (OR-merge)</td>
</tr>
<tr>
<td><code>maxLatticeSignal(initial?)</code></td>
<td>Numeric lattice signal (max-merge)</td>
</tr>
<tr>
<td><code>$state</code></td>
<td>State bag shorthand accessor (SFC-internal)</td>
</tr>
</tbody></table>
<h2>@state macro collection forms</h2>
<table>
<thead>
<tr>
<th>Macro</th>
<th>v2 collection-form syntax</th>
</tr>
</thead>
<tbody><tr>
<td><code>$prop</code></td>
<td><code>$prop: { name: { default: value, type?: &quot;T&quot;, describe?: &quot;...&quot;, expose?: { read?: true, write?: true } } }</code></td>
</tr>
<tr>
<td><code>$computed</code></td>
<td><code>$computed: { name: { value: () =&gt; expr } }</code></td>
</tr>
<tr>
<td><code>$action</code></td>
<td><code>$action: { name: { handler: (args) =&gt; expr, describe?: &quot;...&quot;, expose?: { write?: true } } }</code></td>
</tr>
<tr>
<td><code>$resource</code></td>
<td><code>$resource: { name: { source: () =&gt; fetcher() } }</code></td>
</tr>
<tr>
<td><code>$effect</code></td>
<td><code>$effect { ... }</code> (anonymous) or <code>$effect.on(dep) { ... }</code> (scoped)</td>
</tr>
<tr>
<td><code>$lifecycle</code></td>
<td><code>$lifecycle: { mount: () =&gt; ..., dispose: () =&gt; ... }</code></td>
</tr>
</tbody></table>
<h2>@agent macro collection forms</h2>
<table>
<thead>
<tr>
<th>Macro</th>
<th>v2 collection-form syntax</th>
</tr>
</thead>
<tbody><tr>
<td><code>$describe</code></td>
<td><code>$describe: &quot;human-readable description of the agent&quot;</code></td>
</tr>
<tr>
<td><code>$action</code></td>
<td><code>$action: { name: { expose: true, describe?: &quot;...&quot; } }</code></td>
</tr>
</tbody></table>
<h2>@aihu/arbor</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>branch(tag, attrs, children)</code></td>
<td>Create a reactive element branch</td>
</tr>
<tr>
<td><code>leaf(signal)</code></td>
<td>Create a reactive text node</td>
</tr>
<tr>
<td><code>mount(root, tree)</code></td>
<td>Mount a component tree onto a DOM node</td>
</tr>
<tr>
<td><code>slot(opts, children)</code></td>
<td>Slot boundary primitive</td>
</tr>
<tr>
<td><code>hydrate(root, tree)</code></td>
<td>Hydrate a server-rendered root</td>
</tr>
<tr>
<td><code>materialize(descriptor)</code></td>
<td>Materialize a component descriptor</td>
</tr>
</tbody></table>
<h2>@aihu/runtime</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>onMount(fn)</code></td>
<td>Register a callback to run after component mounts</td>
</tr>
<tr>
<td><code>onCleanup(fn)</code></td>
<td>Register a callback to run when component unmounts</td>
</tr>
</tbody></table>
<h2>@aihu/router</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>createRouter(routes)</code></td>
<td>Create a file-based router from compiler-emitted route definitions</td>
</tr>
<tr>
<td><code>defineRouterMiddleware(fn)</code></td>
<td>Define a client-side router middleware</td>
</tr>
<tr>
<td><code>composeRouterMiddleware(...fns)</code></td>
<td>Compose router middleware with stage ordering</td>
</tr>
<tr>
<td><code>RouteDefinition</code></td>
<td>Type: a route definition object</td>
</tr>
</tbody></table>
<h2>@aihu/router/plugin</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>viteRouterIntegration(opts?)</code></td>
<td>Vite plugin: scan pages + emit route manifest</td>
</tr>
<tr>
<td><code>scanPages(dir)</code></td>
<td>Scan src/pages/ for .aihu files + .route.json sidecars</td>
</tr>
<tr>
<td><code>scanLayouts(dir)</code></td>
<td>Scan src/layouts/ for .aihu layout files</td>
</tr>
<tr>
<td><code>readRouteSidecar(path)</code></td>
<td>Read a .route.json sidecar file</td>
</tr>
</tbody></table>
<h2>@aihu/server</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>defineRoute(opts)</code></td>
<td>Define a server route handler</td>
</tr>
<tr>
<td><code>createRequestRouter(manifest, opts?)</code></td>
<td>Create a fetch-API request handler from a route manifest</td>
</tr>
<tr>
<td><code>defineMiddleware(fn)</code></td>
<td>Server middleware</td>
</tr>
<tr>
<td><code>composeMiddleware(...fns)</code></td>
<td>Compose server middleware</td>
</tr>
<tr>
<td><code>defineApiRoute(opts)</code></td>
<td>Define a REST API route</td>
</tr>
<tr>
<td><code>json(data, status?)</code></td>
<td>Return a JSON response</td>
</tr>
<tr>
<td><code>notFound(msg?)</code></td>
<td>Return a 404 response</td>
</tr>
<tr>
<td><code>renderToStream(component, opts)</code></td>
<td>Stream-render a component to HTML</td>
</tr>
<tr>
<td><code>renderToString(loader)</code></td>
<td>String-render a server component</td>
</tr>
<tr>
<td><code>defineLoader(fn)</code></td>
<td>Define a server-side data loader</td>
</tr>
<tr>
<td><code>defineAihuConfig(config)</code></td>
<td>Define the aihu app configuration</td>
</tr>
<tr>
<td><code>createServerCall&lt;A, R&gt;(endpoint)</code></td>
<td>Create a typed client fetch stub</td>
</tr>
<tr>
<td><code>BuildTarget</code></td>
<td>Type: <code>&#39;client&#39; | &#39;server&#39; | &#39;universal&#39;</code></td>
</tr>
</tbody></table>
<h2>@aihu/agent</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>defineAgent(opts)</code></td>
<td>Register an agent definition</td>
</tr>
<tr>
<td><code>AgentRegistry</code></td>
<td>Agent registry type</td>
</tr>
</tbody></table>
<h2>@aihu/agent-service</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>AgentService</code></td>
<td>Agent service adapter class</td>
</tr>
<tr>
<td><code>defineAgentService(opts)</code></td>
<td>Create an agent service instance</td>
</tr>
</tbody></table>
<h2>@aihu/agent-readiness</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>viteAgentReadinessIntegration(opts?)</code></td>
<td>Vite plugin for MCP/agent readiness</td>
</tr>
</tbody></table>
<h2>@aihu/data</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>createDataPlugin(opts)</code></td>
<td>Create a data plugin instance</td>
</tr>
</tbody></table>
<h2>@aihu/plugin</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>definePlugin(opts)</code></td>
<td>Define a aihu plugin</td>
</tr>
<tr>
<td><code>validatePlugin(plugin)</code></td>
<td>Validate a plugin at build time</td>
</tr>
<tr>
<td><code>Plugin</code></td>
<td>Plugin interface type</td>
</tr>
<tr>
<td><code>BuildTarget</code></td>
<td>Build target type</td>
</tr>
</tbody></table>
<h2>@aihu/cli</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>scaffoldApp(name, dir)</code></td>
<td>Scaffold a new aihu application</td>
</tr>
<tr>
<td><code>scaffoldPage(route, dir)</code></td>
<td>Add a page to an existing project</td>
</tr>
<tr>
<td><code>scaffoldComponent(name, dir)</code></td>
<td>Scaffold a .aihu component</td>
</tr>
<tr>
<td><code>scaffoldPlugin(name, dir)</code></td>
<td>Scaffold a plugin package skeleton</td>
</tr>
<tr>
<td><code>migrateFile(content)</code></td>
<td>Convert HTML-tag SFC content to @blockname{}</td>
</tr>
<tr>
<td><code>migrateFiles(files, dryRun, cwd)</code></td>
<td>Migrate files in-place or dry-run</td>
</tr>
</tbody></table>
<h2>@aihu/context</h2>
<table>
<thead>
<tr>
<th>Export</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>createContext&lt;T&gt;(key)</code></td>
<td>Create a scoped context cell</td>
</tr>
<tr>
<td><code>getContext&lt;T&gt;(key)</code></td>
<td>Read a context value</td>
</tr>
<tr>
<td><code>setContext&lt;T&gt;(key, value)</code></td>
<td>Set a context value</td>
</tr>
</tbody></table>
`,
  },
  'authoring-agents': {
    title: 'Authoring Agents',
    html: `<h1>Authoring Agents</h1>
<p>aihu is agent-first. Every <code>.aihu</code> component can expose MCP-compatible tools and resources via the <code>@agent</code> block. The <code>@aihu/agent</code>, <code>@aihu/agent-service</code>, and <code>@aihu/agent-readiness</code> packages form the agent layer.</p>
<h2>The <code>@agent</code> block</h2>
<p>Add an <code>@agent</code> block to any <code>.aihu</code> SFC to expose agent capabilities:</p>
<pre><code>@agent {
  $describe: &quot;The main application agent&quot;
  $action: {
    greet: { expose: true, describe: &quot;Greet a user by name&quot; }
    getUser: { expose: true, describe: &quot;Fetch a user by ID&quot; }
  }
}
</code></pre>
<h3>Directives</h3>
<ul>
<li><strong><code>$describe: &quot;text&quot;</code></strong> — a human-readable description of the agent. Included in the MCP manifest.</li>
<li><strong><code>$action: { name: { expose: true, describe: &quot;...&quot; } }</code></strong> — expose an action as an MCP tool. The compiler generates the MCP tool descriptor and wires the implementation to the component&#39;s action method of the same name. Use <code>expose: true</code> to expose with default settings, or <code>expose: { read: true }</code> / <code>expose: { write: true }</code> for fine-grained control.</li>
</ul>
<h3>Client build elision</h3>
<p>When compiling with <code>BuildTarget.Client</code>, the <code>@agent</code> block is fully elided — no manifest JSON is emitted and the JS output contains a <code>// [client build] @agent block elided</code> comment. Agent code never reaches the browser bundle.</p>
<h2><code>@aihu/agent</code></h2>
<p>The <code>@aihu/agent</code> package provides the registry and registration primitives:</p>
<pre><code class="language-typescript">import { defineAgent } from &#39;@aihu/agent&#39;

const agent = defineAgent({
  name: &#39;my-agent&#39;,
  tools: [
    {
      name: &#39;greet&#39;,
      description: &#39;Greet a user&#39;,
      inputSchema: { type: &#39;object&#39;, properties: { name: { type: &#39;string&#39; } } },
      handler: async ({ name }) =&gt; ({ message: \`Hello, \${name}!\` }),
    },
  ],
})
</code></pre>
<p><code>AgentRegistry</code> holds registered agent definitions. Each <code>defineAgent</code> call returns an <code>AgentDefinition</code> that can be passed to <code>AgentService</code>.</p>
<h2><code>@aihu/agent-service</code></h2>
<p>The <code>@aihu/agent-service</code> package adapts agent definitions to a runtime service:</p>
<pre><code class="language-typescript">import { defineAgentService } from &#39;@aihu/agent-service&#39;
import { myAgent } from &#39;./agents/my-agent.ts&#39;

const service = defineAgentService({
  agent: myAgent,
  transport: &#39;http&#39;,
  port: 3001,
})
</code></pre>
<p><code>AgentService</code> handles request routing, rate limiting, and MCP protocol serialization.</p>
<h2><code>@aihu/agent-readiness</code> — Vite integration</h2>
<p>In development and build, use <code>viteAgentReadinessIntegration()</code> to wire agent manifests into the Vite build:</p>
<pre><code class="language-typescript">// vite.config.ts
import { defineConfig } from &#39;vite&#39;
import { viteAgentReadinessIntegration } from &#39;@aihu/agent-readiness&#39;

export default defineConfig({
  plugins: [
    viteAgentReadinessIntegration(),
  ],
})
</code></pre>
<p>The plugin:</p>
<ol>
<li>Reads <code>manifest_json</code> from each compiled SFC that has an <code>@agent</code> block.</li>
<li>Aggregates tool/resource descriptors into a single <code>agent-manifest.json</code> asset.</li>
<li>Emits an <code>llms.txt</code> file at the root of the output for MCP discovery.</li>
</ol>
<p>The <code>llms.txt</code> and MCP manifest are part of the aihu contract — every aihu application ships them.</p>
`,
  },
  'authoring-components': {
    title: 'Authoring Components',
    html: `<h1>Authoring Components</h1>
<p>A <code>.aihu</code> Single File Component (SFC) is composed of named blocks. Each block uses the <code>@blockname { ... }</code> syntax introduced in v0.5.</p>
<h2>@state block</h2>
<p>The <code>@state</code> block declares the reactive contract of the component.</p>
<h3>Macros</h3>
<ul>
<li><code>$prop: { name: { default: value, ... } }</code> — a public property. Settable from HTML attributes. Reactive. Use <code>expose: { read: true }</code> and/or <code>expose: { write: true }</code> to expose the prop to agents.</li>
<li><code>$computed: { name: { value: () =&gt; expr } }</code> — a derived signal. Re-evaluates when its dependencies change.</li>
<li><code>$resource: { name: { source: () =&gt; fetcher(signal) } }</code> — binds an async resource to a signal. Returns a 3-state loader: <code>{ pending, value, error }</code>.</li>
<li><code>$effect { ... }</code> — runs a side effect when tracked signals change. Use <code>$effect.on(dep)</code> to scope to a specific dependency.</li>
<li><code>$lifecycle: { mount: () =&gt; ..., dispose: () =&gt; ... }</code> — lifecycle hooks; <code>mount</code> runs after first DOM mount, <code>dispose</code> runs on unmount.</li>
<li><code>$action: { name: { handler: (args) =&gt; ..., ... } }</code> — a named action method on the component. Use <code>expose: { write: true }</code> to expose to agents.</li>
</ul>
<h3>Example</h3>
<pre><code>@state {
  $prop: {
    count: { default: 0, type: &quot;number&quot; }
  }

  $computed: {
    doubled: { value: () =&gt; count() * 2 }
  }

  $effect { console.log(&#39;count is&#39;, count()) }

  $lifecycle: {
    mount: () =&gt; console.log(&#39;mounted&#39;)
  }

  $action: {
    increment: { handler: () =&gt; count(count() + 1) }
  }
}
</code></pre>
<h2>@template block</h2>
<p>The <code>@template</code> block defines the DOM output using aihu&#39;s template DSL.</p>
<h3>Interpolation</h3>
<ul>
<li><code>{{ expr }}</code> — reactive text node. Uses <code>nodeValue</code> for targeted updates.</li>
</ul>
<h3>Attribute bindings</h3>
<ul>
<li><code>$attr:name=&quot;expr&quot;</code> — bind an attribute to a reactive expression.</li>
<li><code>$on:event=&quot;handler&quot;</code> — attach an event listener.</li>
<li><code>$ref:name</code> — capture a DOM element reference into the state bag.</li>
</ul>
<h3>Conditional rendering</h3>
<ul>
<li><code>$show=&quot;cond&quot;</code> — toggle display without removing from DOM.</li>
<li><code>$when=&quot;cond&quot;</code> ... <code>$else</code> — conditional branch; removes/inserts DOM nodes.</li>
</ul>
<h3>List rendering</h3>
<ul>
<li><code>$each=&quot;item of list&quot;</code> — render a list. Keyed by identity by default.</li>
</ul>
<h3>Special elements</h3>
<p><strong><code>&lt;$slot&gt;</code></strong> — inserts slotted children provided by the parent:</p>
<pre><code class="language-html">&lt;$slot name=&quot;header&quot; /&gt;
</code></pre>
<p><strong><code>&lt;$suspense&gt;</code></strong> — wraps an async resource with a loading fallback:</p>
<pre><code class="language-html">&lt;$suspense source={resource} fallback={&lt;span&gt;Loading...&lt;/span&gt;}&gt;
  &lt;span&gt;{{ resource.value.name }}&lt;/span&gt;
&lt;/$suspense&gt;
</code></pre>
<p>Backed by <code>createSuspenseBoundary(source, fallback, loaded)</code> from <code>@aihu/arbor</code>.</p>
<p><strong><code>&lt;$shield&gt;</code></strong> — isolates a subtree behind a shield boundary:</p>
<pre><code class="language-html">&lt;$shield&gt;
  &lt;template #main&gt;&lt;div&gt;Main content&lt;/div&gt;&lt;/template&gt;
  &lt;template #fallback&gt;&lt;div&gt;Shield fallback&lt;/div&gt;&lt;/template&gt;
&lt;/$shield&gt;
</code></pre>
<p>Backed by <code>createShieldBoundary(() =&gt; main, (shield) =&gt; fallback)</code>.</p>
<p><strong><code>&lt;$guard&gt;</code></strong> — conditionally renders based on a check function:</p>
<pre><code class="language-html">&lt;$guard check={isAuthenticated}&gt;
  &lt;template #main&gt;&lt;div&gt;Protected content&lt;/div&gt;&lt;/template&gt;
  &lt;template #fallback&gt;&lt;div&gt;Please log in&lt;/div&gt;&lt;/template&gt;
&lt;/$guard&gt;
</code></pre>
<p>Backed by <code>createGuardBoundary(check, () =&gt; main, (guard) =&gt; fallback)</code>.</p>
<p><strong><code>&lt;$warp&gt;</code></strong> — renders children into a portal target (stub in v0.5):</p>
<pre><code class="language-html">&lt;$warp target=&quot;#modal-root&quot;&gt;
  &lt;div&gt;Portal content&lt;/div&gt;
&lt;/$warp&gt;
</code></pre>
<p>Backed by <code>createWarpBoundary(target, () =&gt; children)</code>.</p>
<h2>@style block</h2>
<p>The <code>@style</code> block defines component-scoped styles with reactive capabilities.</p>
<ul>
<li><code>$reactive</code> — marks a CSS property as driven by a signal.</li>
<li><code>$media</code> — a responsive breakpoint block.</li>
<li><code>$when</code> — conditional style application.</li>
</ul>
<pre><code>@style {
  :host {
    color: $reactive(textColor);
  }
  $media (max-width: 600px) {
    :host { font-size: 14px; }
  }
  $when (isDark) {
    :host { background: #111; }
  }
}
</code></pre>
<h2>@agent block</h2>
<p>The <code>@agent</code> block exposes the component as an MCP agent. See <a href="authoring-agents.md">Authoring Agents</a> for full details.</p>
<pre><code>@agent {
  $describe: &quot;Greeting agent for the home page&quot;
  $action: {
    greet: { expose: true, describe: &quot;Greet a user by name&quot; }
  }
}
</code></pre>
`,
  },
  'authoring-plugins': {
    title: 'Authoring Plugins',
    html: `<h1>Authoring Plugins</h1>
<p>aihu plugins extend the compiler with new blocks, macros, component boundaries, and transforms. Every plugin must be explicitly registered — auto-discovery is forbidden per Plugin Contract Spec §7.2.</p>
<h2>Defining a plugin</h2>
<p>Use <code>definePlugin</code> from <code>@aihu/plugin</code>:</p>
<pre><code class="language-typescript">import { definePlugin } from &#39;@aihu/plugin&#39;

export const myPlugin = definePlugin({
  name: &#39;my-plugin&#39;,
  version: &#39;1.0.0&#39;,
  namespace: &#39;my&#39;,
  contributes: {
    blocks: [&#39;my-block&#39;],
    macros: [&#39;$my-macro&#39;],
    components: [&#39;&lt;$my-element&gt;&#39;],
    transforms: [myTransform],
  },
})
</code></pre>
<h3><code>contributes</code> fields</h3>
<ul>
<li><strong><code>blocks</code></strong> — additional <code>@blockname { }</code> block types this plugin handles. The compiler routes these to the plugin&#39;s parser.</li>
<li><strong><code>macros</code></strong> — <code>$macro</code> names this plugin contributes to <code>@state</code> blocks.</li>
<li><strong><code>components</code></strong> — special template elements (e.g. <code>&lt;$my-element&gt;</code>) this plugin provides.</li>
<li><strong><code>transforms</code></strong> — build-time AST transform functions applied after parsing.</li>
</ul>
<h3><code>serverOnly</code></h3>
<p>Set <code>Plugin.serverOnly: true</code> to mark a plugin as server-build only. The client build pipeline will skip it entirely:</p>
<pre><code class="language-typescript">export const loaderPlugin = definePlugin({
  name: &#39;loader-plugin&#39;,
  version: &#39;1.0.0&#39;,
  namespace: &#39;loader&#39;,
  serverOnly: true,
  contributes: { transforms: [serverLoaderTransform] },
})
</code></pre>
<h2>Validating a plugin</h2>
<p>Call <code>validatePlugin(plugin)</code> at build time to verify the plugin definition is structurally correct:</p>
<pre><code class="language-typescript">import { validatePlugin } from &#39;@aihu/plugin&#39;

validatePlugin(myPlugin) // throws if invalid
</code></pre>
<p><code>validatePlugin</code> checks:</p>
<ul>
<li><code>name</code> and <code>version</code> are non-empty strings.</li>
<li><code>namespace</code> contains only alphanumeric characters and hyphens.</li>
<li>All <code>contributes</code> arrays contain valid identifiers.</li>
<li>No duplicate block or macro names within the namespace.</li>
</ul>
<h2>Registering a plugin</h2>
<p>Plugins are registered in <code>defineAihuConfig</code> in your app&#39;s config file:</p>
<pre><code class="language-typescript">import { defineAihuConfig } from &#39;@aihu/server&#39;
import { myPlugin } from &#39;./plugins/my-plugin.ts&#39;

export default defineAihuConfig({
  plugins: [myPlugin],
  build: {
    target: &#39;universal&#39;,
  },
})
</code></pre>
<p>Per Plugin Contract Spec §7.2, plugins <strong>must</strong> be listed in the explicit <code>plugins</code> array. There is no filesystem scanning, package.json detection, or magic import resolution. This keeps build behavior deterministic and auditable.</p>
<h2>Plugin lifecycle</h2>
<ol>
<li><code>defineAihuConfig</code> collects all plugins.</li>
<li>At build start, <code>validatePlugin</code> is called for each registered plugin.</li>
<li>The Rust compiler receives the plugin manifest and routes block/macro names to the appropriate handlers.</li>
<li><code>contributes.transforms</code> are applied as post-parse AST passes.</li>
<li>Server-only plugins are filtered out before the client build pipeline.</li>
</ol>
`,
  },
  'data-fetching': {
    title: 'Data Fetching',
    html: `<h1>Data Fetching</h1>
<p>aihu provides several primitives for fetching data, ranging from reactive resource signals to server-side loaders and typed client stubs.</p>
<h2><code>$resource</code> macro</h2>
<p>In a <code>@state</code> block, <code>$resource</code> binds an async fetcher to a reactive signal:</p>
<pre><code>@state {
  $prop: {
    userId: { default: 1, type: &quot;number&quot; }
  }

  $resource: {
    user: { source: () =&gt; fetchUser(userId()) }
  }
}
</code></pre>
<p>The <code>user</code> variable is a 3-state loader object:</p>
<ul>
<li><code>user.pending</code> — <code>true</code> while the fetch is in-flight.</li>
<li><code>user.value</code> — the resolved value (or <code>undefined</code> if pending/error).</li>
<li><code>user.error</code> — the error (or <code>undefined</code> if pending/success).</li>
</ul>
<p>When <code>userId</code> changes, the resource re-fetches automatically.</p>
<h2><code>createResource</code> from <code>@aihu/runtime</code></h2>
<p>Use <code>createResource</code> directly in TypeScript outside of SFCs:</p>
<pre><code class="language-typescript">import { createResource } from &#39;@aihu/runtime&#39;
import { signal } from &#39;@aihu/signals&#39;

const userId = signal(1)
const user = createResource(() =&gt; fetch(\`/api/users/\${userId()}\`).then(r =&gt; r.json()))
</code></pre>
<p>The resource is automatically re-fetched when any signals read inside the fetcher change.</p>
<h2>Server loaders</h2>
<p>Server loaders run on the server and provide data to SSR-rendered pages. Define a loader with <code>defineLoader</code> from <code>@aihu/server</code>:</p>
<pre><code class="language-typescript">import { defineLoader } from &#39;@aihu/server&#39;

export const loader = defineLoader(async (ctx) =&gt; {
  const users = await db.users.findMany()
  return { users }
})
</code></pre>
<p>The loader receives a <code>LoaderContext</code> with the request, params, and URL. Return value is serialized and sent to the client as part of the SSR payload.</p>
<h2>Server loaders → SFC handoff</h2>
<p>A loader runs server-side per matched route, but the SFC author still has to consume its result. There are two documented handoff patterns; pick whichever matches your component&#39;s data flow.</p>
<h3>Pattern A — <code>route.data</code> prop (default)</h3>
<p>The loader payload is delivered as the <code>data</code> field on the SFC&#39;s <code>route</code> prop. This is the most common pattern and what every page route gets for free.</p>
<p><code>src/pages/posts/[slug].loader.ts</code>:</p>
<pre><code class="language-typescript">import { defineLoader } from &#39;@aihu/server&#39;

export const loader = defineLoader(async (ctx) =&gt; {
  return await db.posts.findOne({ slug: ctx.params.slug })
})
</code></pre>
<p><code>src/pages/posts/[slug].aihu</code>:</p>
<pre><code>@route { path: &quot;/posts/[slug]&quot;, ssr: true }

@state {
  $prop: {
    route: { type: &quot;{ params: { slug: string }; data: { title: string; body: string } }&quot; }
  }
}

@template {
  &lt;article&gt;
    &lt;h1&gt;{route().data.title}&lt;/h1&gt;
    &lt;p&gt;{route().data.body}&lt;/p&gt;
  &lt;/article&gt;
}
</code></pre>
<p>The runtime injects the resolved loader payload as <code>route.data</code> before mount. During streaming SSR or client-side re-validation, wrap the consumer in <code>&lt;$suspense&gt;</code> to declaratively handle the pending state — see <a href="#the-3-state-loader-pattern">the 3-state loader pattern</a> below.</p>
<p>A worked end-to-end example lives at <a href="https://github.com/fellwork/aihu/tree/main/examples/blog-loader"><code>examples/blog-loader/</code></a>.</p>
<h3>Pattern B — <code>$resource</code> + <code>createServerCall</code></h3>
<p>If the data needs to be fetched <em>on demand</em> (e.g. on a button click or when a search box changes), skip the loader and use a typed client stub instead. <code>createServerCall</code> returns a function that posts to a server-registered action.</p>
<pre><code class="language-typescript">// shared/api.ts
import { createServerCall } from &#39;@aihu/server&#39;
import type { Post } from &#39;./types&#39;

export const getPost = createServerCall&lt;[slug: string], Post&gt;(&#39;posts/getPost&#39;)
</code></pre>
<pre><code>@state {
  $prop: {
    searchTerm: { default: &quot;&#39;&#39;&quot;, type: &quot;string&quot; }
  }

  $resource: {
    // refetches when searchTerm changes
    matches: { source: () =&gt; getPost(searchTerm()) }
  }
}

@template {
  &lt;input $bind:value=&quot;searchTerm&quot; /&gt;

  &lt;$suspense source=&quot;matches&quot;&gt;
    &lt;$slot name=&quot;fallback&quot;&gt;&lt;span&gt;Searching...&lt;/span&gt;&lt;/$slot&gt;
    &lt;ul&gt;
      &lt;li $each=&quot;matches.value as p&quot; $key=&quot;p.slug&quot;&gt;{p.title}&lt;/li&gt;
    &lt;/ul&gt;
  &lt;/$suspense&gt;
}
</code></pre>
<p>Use Pattern A when the data is route-bound and known at request time. Use Pattern B when the data depends on UI state that the user changes after the page loads.</p>
<h2><code>$server</code> macro</h2>
<p>In <code>@state</code> blocks, <code>$server</code> gates code to server-only execution:</p>
<pre><code>@state {
  const data = $server.fetchSecretData()
}
</code></pre>
<p>When compiling with <code>BuildTarget.Client</code>, any <code>$server</code> references are elided from the output and replaced with a <code>// [client build] $server macro reference elided</code> comment.</p>
<h2><code>createServerCall</code></h2>
<p><code>createServerCall</code> creates a typed fetch stub that calls a server action from client-side code:</p>
<pre><code class="language-typescript">import { createServerCall } from &#39;@aihu/server&#39;

const getUser = createServerCall&lt;[id: number], User&gt;(&#39;users/getUser&#39;)

// In an effect or event handler:
const user = await getUser(42)
</code></pre>
<p>The stub sends a <code>POST</code> request to <code>/_aihu/call/&lt;endpoint&gt;</code> with the args serialized as JSON. The server routes it to the registered action and returns the typed response.</p>
<h2>The 3-state loader pattern</h2>
<p>All async data in aihu follows the 3-state pattern:</p>
<table>
<thead>
<tr>
<th>State</th>
<th><code>pending</code></th>
<th><code>value</code></th>
<th><code>error</code></th>
</tr>
</thead>
<tbody><tr>
<td>Loading</td>
<td><code>true</code></td>
<td><code>undefined</code></td>
<td><code>undefined</code></td>
</tr>
<tr>
<td>Success</td>
<td><code>false</code></td>
<td>data</td>
<td><code>undefined</code></td>
</tr>
<tr>
<td>Error</td>
<td><code>false</code></td>
<td><code>undefined</code></td>
<td>Error</td>
</tr>
</tbody></table>
<p>Use <code>&lt;$suspense&gt;</code> in templates to handle the pending state declaratively:</p>
<pre><code class="language-html">&lt;$suspense source={user} fallback={&lt;span&gt;Loading user...&lt;/span&gt;}&gt;
  &lt;div&gt;{{ user.value.name }}&lt;/div&gt;
&lt;/$suspense&gt;
</code></pre>
`,
  },
  deployment: {
    title: 'Deployment',
    html: `<h1>Deployment</h1>
<h2>Bun (recommended)</h2>
<pre><code class="language-bash">bun run build
bun run preview
</code></pre>
<p><code>bun run build</code> compiles all <code>.aihu</code> SFCs, bundles with Vite/Rolldown, and validates size budgets. <code>bun run preview</code> serves the production build locally using Bun&#39;s built-in HTTP server.</p>
<h2>Node.js</h2>
<p>aihu output is standard ESM. Any Node.js ≥20.18.0 runtime can serve a aihu application:</p>
<pre><code class="language-bash">npm run build
node dist/server/entry.js
</code></pre>
<p>The server entry is generated by the universal build and uses <code>@aihu/server</code>&#39;s request router.</p>
<h2>Cloudflare Workers and Vercel Edge</h2>
<p>aihu uses only Web Standard APIs (Fetch, ReadableStream, URL) in its server runtime, making it compatible with edge environments.</p>
<p>Set the <code>AIHU_NATIVE_SKIP</code> environment variable to disable any Node.js-specific compatibility shims:</p>
<pre><code class="language-bash">AIHU_NATIVE_SKIP=1 bun run build
</code></pre>
<p>Deploy the <code>dist/server/</code> output as a Worker or Edge Function. The <code>@aihu/server</code> request router handles incoming <code>Request</code> objects and returns <code>Response</code> objects natively — no adapter layer needed.</p>
<h2><code>defineAihuConfig</code></h2>
<p>The app configuration lives in <code>aihu.config.ts</code> (or exported from <code>vite.config.ts</code>):</p>
<pre><code class="language-typescript">import { defineAihuConfig } from &#39;@aihu/server&#39;

export default defineAihuConfig({
  build: {
    target: &#39;universal&#39;,
    outDir: &#39;dist&#39;,
    sourcemap: false,
  },
  plugins: [],
})
</code></pre>
<h2><code>@aihu/server</code> request router</h2>
<p>The <code>createRequestRouter</code> handles edge function dispatch:</p>
<pre><code class="language-typescript">import { createRequestRouter } from &#39;@aihu/server&#39;
import routes from &#39;virtual:aihu-routes&#39;

const router = createRequestRouter({ routes })

export default {
  fetch(request: Request): Response | Promise&lt;Response&gt; {
    return router.handle(request)
  },
}
</code></pre>
<h2><code>viteRouterIntegration()</code> at build time</h2>
<p>The Vite plugin performs these steps at build time:</p>
<ol>
<li><code>scanPages(dir)</code> — discovers all <code>.aihu</code> files under <code>src/pages/</code>.</li>
<li>For each page, reads the <code>.route.json</code> sidecar emitted by the Rust compiler.</li>
<li>Assembles the route manifest into the <code>virtual:aihu-routes</code> module.</li>
<li>Emits <code>dist/routes.json</code> for runtime consumption.</li>
</ol>
<p>This means route manifests are fully static after build — no filesystem scanning at runtime.</p>
<h2>Size budgets</h2>
<p>The browser bundle has a hard ceiling at 3.46 kB gz. Every build validates against the size limits in <code>.size-limit.ts</code>. Exceeding the limit fails the build.</p>
<p>Run <code>bun run size</code> to check current bundle sizes without running a full build.</p>
`,
  },
  'getting-started': {
    title: 'Getting Started',
    html: `<h1>Getting Started</h1>
<h2>Hello World walkthrough</h2>
<p>After scaffolding (see <a href="installation.md">Installation</a>), open <code>src/pages/index.aihu</code>. The v0.8 template looks like this:</p>
<pre><code>@state {
  $prop: {
    name: { default: &quot;&#39;world&#39;&quot;, type: &quot;string&quot; }
  }
}

@template {
  &lt;div&gt;Hello {{ name }}&lt;/div&gt;
}

@route {
  path: /
  name: home
}
</code></pre>
<h3>The <code>@state</code> block</h3>
<p><code>@state</code> declares the reactive state for the component:</p>
<ul>
<li><code>$prop: { name: { default: &quot;&#39;world&#39;&quot;, type: &quot;string&quot; } }</code> — declares a component property named <code>name</code> with a default value of <code>&#39;world&#39;</code>. Props are reactive and can be set from outside the component as HTML attributes.</li>
</ul>
<p>You can add computed values and effects in the same block:</p>
<pre><code>@state {
  $prop: {
    name: { default: &quot;&#39;world&#39;&quot;, type: &quot;string&quot; }
  }

  $computed: {
    greeting: { value: () =&gt; \`Hello, \${name()}!\` }
  }

  $effect { console.log(&#39;name changed to&#39;, name()) }
}
</code></pre>
<h3>The <code>@template</code> block</h3>
<p><code>@template</code> defines the component&#39;s DOM structure using aihu&#39;s template DSL:</p>
<ul>
<li><code>{{ expr }}</code> — interpolates a reactive expression. Updates use <code>nodeValue</code> for 122× faster targeted writes.</li>
<li><code>$attr:foo=&quot;val&quot;</code> — binds an attribute reactively.</li>
<li><code>$on:click=&quot;handler&quot;</code> — attaches an event listener.</li>
<li><code>$show</code> — toggles visibility based on a boolean signal.</li>
<li><code>$each</code> — renders a list of items.</li>
</ul>
<h3>The <code>@route</code> block</h3>
<p><code>@route</code> registers the component as a page route:</p>
<pre><code>@route {
  path: /
  name: home
}
</code></pre>
<p>During build, the Rust compiler emits a <code>.route.json</code> sidecar alongside each compiled SFC. <code>viteRouterIntegration()</code> in <code>vite.config.ts</code> reads these sidecars at build time and assembles the route manifest.</p>
<h3>HMR in development</h3>
<p>In dev mode, Vite watches <code>.aihu</code> files. When you save a change, only the affected reactive subtree is re-evaluated — no full page reload needed. Edit the <code>name</code> default value or the template expression and the browser updates immediately.</p>
<h2>Next steps</h2>
<ul>
<li><a href="authoring-components.md">Authoring Components</a> — full reference for <code>@state</code>, <code>@template</code>, and <code>@style</code> blocks.</li>
<li><a href="routing-layouts.md">Routing and Layouts</a> — file-based routing, layouts, and middleware.</li>
<li><a href="reactivity.md">Reactivity</a> — the signals, computed, and effect primitives.</li>
</ul>
`,
  },
  installation: {
    title: 'Installation',
    html: `<h1>Installation</h1>
<h2>Prerequisites</h2>
<p>aihu requires one of the following runtimes:</p>
<ul>
<li><strong>Bun</strong> ≥1.3.0 (recommended — faster installs, native TypeScript, built-in test runner)</li>
<li><strong>Node.js</strong> ≥20.18.0 with a package manager of your choice (npm, pnpm, or yarn)</li>
</ul>
<h2>Scaffold a new application</h2>
<p>Use the <code>npx aihu</code> CLI to generate a new project from the Hello World template:</p>
<pre><code class="language-bash">npx aihu app my-app
</code></pre>
<p>The scaffolder generates six files:</p>
<pre><code>my-app/
  package.json
  tsconfig.json
  vite.config.ts
  src/
    main.ts
    pages/
      index.aihu
</code></pre>
<ul>
<li><strong><code>package.json</code></strong> — workspace manifest with <code>@aihu/runtime</code>, <code>@aihu/signals</code>, <code>@aihu/arbor</code>, and <code>@aihu/router</code> as dependencies, plus Vite and the aihu Vite plugin as devDependencies.</li>
<li><strong><code>tsconfig.json</code></strong> — extends the aihu base TypeScript config with <code>moduleResolution: bundler</code>.</li>
<li><strong><code>vite.config.ts</code></strong> — Vite config with <code>viteRouterIntegration()</code> wired in.</li>
<li><strong><code>src/main.ts</code></strong> — entry point that calls <code>mount()</code> on <code>document.body</code>.</li>
<li><strong><code>src/pages/index.aihu</code></strong> — the Hello World SFC with <code>@state</code>, <code>@template</code>, and <code>@route</code> blocks.</li>
</ul>
<h2>Install and run</h2>
<pre><code class="language-bash">cd my-app
bun install
bun run dev
</code></pre>
<p>The dev server starts at <code>http://localhost:5173</code> with HMR enabled. Edit <code>src/pages/index.aihu</code> and the browser updates automatically.</p>
<h2>Build for production</h2>
<pre><code class="language-bash">bun run build
bun run preview
</code></pre>
<p><code>bun run build</code> compiles all <code>.aihu</code> files through the Rust SFC compiler, bundles with Vite/Rolldown, and validates against the size budgets defined in <code>.size-limit.ts</code>.</p>
`,
  },
  introduction: {
    title: 'Introduction',
    html: `<h1>Introduction</h1>
<p>aihu is a JavaScript/TypeScript meta-framework for building Web Components with runtime-first reactivity. Applications are authored as <code>.aihu</code> Single File Components (SFCs), compiled to vanilla custom elements, and mounted with sub-2 kB reactive primitives.</p>
<h2>Why aihu</h2>
<ul>
<li><strong>No framework lock-in</strong> — output is vanilla custom elements; any consumer can use them without knowing about aihu.</li>
<li><strong>v3 dep-free thesis</strong> — zero non-<code>@aihu/*</code> runtime dependencies across all packages. Every bundle that ships to a browser or edge runtime is self-contained.</li>
<li><strong>Sub-2 kB reactive core</strong> — <code>@aihu/signals</code> (≤1.97 kB) + <code>@aihu/arbor</code> (≤2.2 kB) together cover signals, computeds, effects, and DOM diffing in a tight envelope.</li>
<li><strong>Targeted updates</strong> — aihu uses <code>nodeValue</code> rather than <code>textContent</code> for reactive text nodes, which is 122× faster on targeted updates.</li>
<li><strong>MCP + agent-first</strong> — <code>@aihu/agent</code> and <code>@aihu/agent-readiness</code> are first-class; every aihu application can expose MCP tool/resource endpoints out of the box.</li>
</ul>
<h2>Package overview</h2>
<table>
<thead>
<tr>
<th>Package</th>
<th>Purpose</th>
<th>Bundle</th>
</tr>
</thead>
<tbody><tr>
<td><code>@aihu/signals</code></td>
<td>Push-based signals, computeds, effects</td>
<td>≤1.97 kB</td>
</tr>
<tr>
<td><code>@aihu/arbor</code></td>
<td>DOM tree primitives: branch/leaf/mount</td>
<td>≤2.2 kB</td>
</tr>
<tr>
<td><code>@aihu/runtime</code></td>
<td>onMount/onCleanup lifecycle</td>
<td>≤1.17 kB</td>
</tr>
<tr>
<td><code>@aihu/router</code></td>
<td>File-based router, middleware</td>
<td>≤1.54 kB</td>
</tr>
<tr>
<td><code>@aihu/server</code></td>
<td>Request router, SSR, loaders</td>
<td>server-only</td>
</tr>
<tr>
<td><code>@aihu/agent</code></td>
<td>Agent/MCP registration</td>
<td>≤200 B</td>
</tr>
<tr>
<td><code>@aihu/agent-service</code></td>
<td>Agent service adapter</td>
<td>≤600 B</td>
</tr>
<tr>
<td><code>@aihu/agent-readiness</code></td>
<td>Vite integration for MCP</td>
<td>build-time</td>
</tr>
<tr>
<td><code>@aihu/data</code></td>
<td>Data plugin adapter</td>
<td>≤800 B</td>
</tr>
<tr>
<td><code>@aihu/plugin</code></td>
<td>Plugin contract types</td>
<td>build-time</td>
</tr>
<tr>
<td><code>@aihu/cli</code></td>
<td>Scaffold CLI</td>
<td>build-time</td>
</tr>
<tr>
<td><code>@aihu/context</code></td>
<td>Shared context primitives</td>
<td>≤300 B</td>
</tr>
</tbody></table>
`,
  },
  reactivity: {
    title: 'Reactivity',
    html: `<h1>Reactivity</h1>
<p><code>@aihu/signals</code> provides the reactive foundation for the entire aihu framework. It uses a push-based, synchronous execution model: when a signal is written, all dependent effects run immediately.</p>
<h2><code>signal&lt;T&gt;(initialValue)</code></h2>
<p>Creates a writable reactive cell:</p>
<pre><code class="language-typescript">import { signal } from &#39;@aihu/signals&#39;

const count = signal(0)

count()       // read: returns 0
count(1)      // write: sets to 1, flushes effects
</code></pre>
<p>Signals are the atomic unit of state. They are not wrapped in objects or proxies — call them as functions to read or write.</p>
<h2><code>computed&lt;T&gt;(fn)</code></h2>
<p>Derives a read-only signal from other signals:</p>
<pre><code class="language-typescript">import { signal, computed } from &#39;@aihu/signals&#39;

const count = signal(0)
const doubled = computed(() =&gt; count() * 2)

doubled() // 0
count(5)
doubled() // 10
</code></pre>
<p>Computed signals are lazily evaluated and memoized. They re-evaluate only when a tracked dependency changes.</p>
<h2><code>effect(fn)</code></h2>
<p>Runs a side effect whenever tracked signals change. Returns a dispose function:</p>
<pre><code class="language-typescript">import { signal, effect } from &#39;@aihu/signals&#39;

const name = signal(&#39;world&#39;)
const dispose = effect(() =&gt; {
  console.log(&#39;Hello,&#39;, name())
})
// Logs: &quot;Hello, world&quot;

name(&#39;aihu&#39;)
// Logs: &quot;Hello, aihu&quot;

dispose() // stops the effect
</code></pre>
<p>Effects run synchronously after each signal write. They auto-track all signals read during their execution.</p>
<h2><code>batch(fn)</code></h2>
<p>Defers effect flushes until the batch function returns:</p>
<pre><code class="language-typescript">import { signal, effect, batch } from &#39;@aihu/signals&#39;

const a = signal(0)
const b = signal(0)

effect(() =&gt; console.log(a(), b()))

batch(() =&gt; {
  a(1)  // no flush yet
  b(2)  // no flush yet
})
// Now effects flush once with a=1, b=2
</code></pre>
<p><code>batch</code> is useful when updating multiple signals that drive the same derived computation — it prevents intermediate renders.</p>
<h2><code>untrack(fn)</code></h2>
<p>Reads signals inside <code>fn</code> without subscribing to them. Re-entrancy safe:</p>
<pre><code class="language-typescript">import { signal, effect, untrack } from &#39;@aihu/signals&#39;

const count = signal(0)
const multiplier = signal(2)

effect(() =&gt; {
  // Only subscribes to count, not multiplier
  const m = untrack(() =&gt; multiplier())
  console.log(count() * m)
})
</code></pre>
<p>Per Learning #46, <code>untrack</code> is re-entrancy safe — calling it from inside an <code>effect</code> or another <code>untrack</code> works correctly.</p>
<h2>Lattice signals</h2>
<p>Lattice signals are merge-monotone reactive cells. They are useful for collaborative state where multiple sources update the same value and the result should be the &quot;join&quot; of all inputs.</p>
<h3><code>latticeSignal&lt;T&gt;(merge, initial)</code></h3>
<p>General-purpose lattice signal with a custom merge function:</p>
<pre><code class="language-typescript">import { latticeSignal } from &#39;@aihu/signals&#39;

const versions = latticeSignal&lt;Set&lt;string&gt;&gt;(
  (a, b) =&gt; new Set([...a, ...b]),
  new Set()
)
</code></pre>
<h3><code>boolLatticeSignal(initial?)</code></h3>
<p>Boolean OR-merge lattice signal. Once set to <code>true</code>, stays <code>true</code>:</p>
<pre><code class="language-typescript">import { boolLatticeSignal } from &#39;@aihu/signals&#39;

const ready = boolLatticeSignal(false)
ready(true)  // true
ready(false) // still true — OR merge
</code></pre>
<h3><code>maxLatticeSignal(initial?)</code></h3>
<p>Numeric max-merge lattice signal. Monotonically increases:</p>
<pre><code class="language-typescript">import { maxLatticeSignal } from &#39;@aihu/signals&#39;

const highScore = maxLatticeSignal(0)
highScore(42)
highScore(10)  // stays 42 — max merge
</code></pre>
<h2><code>$state</code> accessor</h2>
<p><code>$state</code> is a shorthand accessor for the component state bag in SFCs. Inside <code>@state</code> blocks, all declared props and computeds are available on <code>$state</code> without qualification.</p>
<h2>Push-based semantics</h2>
<p>aihu signals are push-based: effects run synchronously after each signal write (or after a <code>batch</code> completes). There is no scheduler, no microtask queue, and no async rendering pipeline. This makes behavior predictable and side effects easy to reason about.</p>
`,
  },
  'routing-layouts': {
    title: 'Routing and Layouts',
    html: `<h1>Routing and Layouts</h1>
<p>aihu uses file-based routing. Pages live under <code>src/pages/</code> and automatically become routes when compiled.</p>
<h2>File-based routing</h2>
<p>Any <code>.aihu</code> file under <code>src/pages/</code> that contains an <code>@route</code> block (or <code>@layout</code> shorthand) is treated as a page route. The file path determines the default URL pattern:</p>
<table>
<thead>
<tr>
<th>File</th>
<th>Default pattern</th>
</tr>
</thead>
<tbody><tr>
<td><code>src/pages/index.aihu</code></td>
<td><code>/</code></td>
</tr>
<tr>
<td><code>src/pages/about.aihu</code></td>
<td><code>/about</code></td>
</tr>
<tr>
<td><code>src/pages/users/[id].aihu</code></td>
<td><code>/users/:id</code></td>
</tr>
</tbody></table>
<h2>The <code>@route</code> block</h2>
<pre><code>@route {
  path: /admin/users
  name: admin-users
  middleware: [auth, admin]
  ssr: true
  layout: admin
}
</code></pre>
<p>Fields:</p>
<ul>
<li><strong><code>path</code></strong> — explicit URL path override. If omitted, the path is derived from the file location.</li>
<li><strong><code>name</code></strong> — route name used in programmatic navigation and the route manifest.</li>
<li><strong><code>middleware</code></strong> — array of middleware names applied to this route.</li>
<li><strong><code>ssr</code></strong> — boolean. <code>true</code> enables server-side rendering for this route.</li>
<li><strong><code>layout</code></strong> — layout name to wrap this route&#39;s content.</li>
</ul>
<h2><code>.route.json</code> sidecars</h2>
<p>The Rust compiler emits a <code>.route.json</code> file alongside each compiled SFC that has an <code>@route</code> block. Example:</p>
<pre><code class="language-json">{
  &quot;pattern&quot;: &quot;/admin/users&quot;,
  &quot;name&quot;: &quot;admin-users&quot;,
  &quot;middleware&quot;: [&quot;auth&quot;, &quot;admin&quot;],
  &quot;ssr&quot;: true,
  &quot;layout&quot;: &quot;admin&quot;
}
</code></pre>
<p>Read a sidecar programmatically with <code>readRouteSidecar(path)</code> from <code>@aihu/router/plugin</code>.</p>
<h2><code>viteRouterIntegration()</code></h2>
<p><code>viteRouterIntegration()</code> is a Vite plugin that scans <code>src/pages/</code> at build time, reads all <code>.route.json</code> sidecars, and assembles a virtual route manifest module:</p>
<pre><code class="language-typescript">// vite.config.ts
import { defineConfig } from &#39;vite&#39;
import { viteRouterIntegration } from &#39;@aihu/router/plugin&#39;

export default defineConfig({
  plugins: [viteRouterIntegration()],
})
</code></pre>
<p>The virtual module <code>virtual:aihu-routes</code> exports the assembled <code>RouteDefinition[]</code> array. The runtime <code>createRequestRouter</code> consumes it to handle navigation.</p>
<h2>Layouts</h2>
<p>Layouts live under <code>src/layouts/</code>. The default layout is <code>src/layouts/default.aihu</code>. A layout wraps the page&#39;s rendered output via <code>&lt;$slot&gt;</code>:</p>
<pre><code>@template {
  &lt;header&gt;My App&lt;/header&gt;
  &lt;main&gt;
    &lt;$slot /&gt;
  &lt;/main&gt;
  &lt;footer&gt;Footer&lt;/footer&gt;
}
</code></pre>
<p><code>scanLayouts(dir)</code> from <code>@aihu/router/plugin</code> returns all discovered layout names.</p>
<h2>Router middleware</h2>
<p>Middleware is defined with <code>defineRouterMiddleware</code> and composed with <code>composeRouterMiddleware</code>:</p>
<pre><code class="language-typescript">import { defineRouterMiddleware, composeRouterMiddleware } from &#39;@aihu/router&#39;

const authMiddleware = defineRouterMiddleware(async (ctx, next) =&gt; {
  if (!ctx.params.token) {
    return { kind: &#39;redirect&#39;, location: &#39;/login&#39;, status: 302 }
  }
  return next()
})

const loggingMiddleware = defineRouterMiddleware(async (ctx, next) =&gt; {
  console.log(&#39;navigating to&#39;, ctx.url.pathname)
  return next()
})

export const composed = composeRouterMiddleware(loggingMiddleware, authMiddleware)
</code></pre>
<h3>Stage ordering</h3>
<p>Middleware passed to <code>composeRouterMiddleware</code> are called in array order. Any middleware that returns a non-void result (e.g. <code>{ kind: &#39;redirect&#39; }</code> or <code>{ kind: &#39;cancel&#39; }</code>) short-circuits the chain — subsequent middleware and the route handler are not called.</p>
<p>Standard stage ordering convention:</p>
<ol>
<li>Logging / tracing</li>
<li>Auth / session</li>
<li>Redirect rules</li>
<li>Render</li>
</ol>
`,
  },
  'ssr-hydration': {
    title: 'SSR and Hydration',
    html: `<h1>SSR and Hydration</h1>
<p>aihu supports server-side rendering via <code>@aihu/server</code>. The build system supports three targets: <code>client</code>, <code>server</code>, and <code>universal</code>.</p>
<h2>Build targets</h2>
<p>Set the build target in <code>defineAihuConfig</code>:</p>
<pre><code class="language-typescript">import { defineAihuConfig } from &#39;@aihu/server&#39;

export default defineAihuConfig({
  build: {
    target: &#39;universal&#39;,
  },
})
</code></pre>
<p>Or via the compiler CLI flag: <code>--target client|server|universal</code>.</p>
<h3><code>BuildTarget</code> values</h3>
<table>
<thead>
<tr>
<th>Target</th>
<th>Description</th>
</tr>
</thead>
<tbody><tr>
<td><code>client</code></td>
<td>Browser bundle only. <code>@agent</code> manifest and <code>$server</code> refs are elided.</td>
</tr>
<tr>
<td><code>server</code></td>
<td>Server bundle only. Full agent manifest and server-only code included.</td>
</tr>
<tr>
<td><code>universal</code></td>
<td>Both client and server outputs. Default.</td>
</tr>
</tbody></table>
<h2><code>renderToStream</code></h2>
<p>Stream-render a component to an HTML response:</p>
<pre><code class="language-typescript">import { renderToStream } from &#39;@aihu/server&#39;

const response = renderToStream(MyComponent, {
  props: { userId: 42 },
  loader: myLoader,
})
</code></pre>
<p>Returns a <code>ReadableStream&lt;string&gt;</code> that emits HTML chunks as the component tree resolves. Suitable for edge runtimes and Node.js streaming responses.</p>
<h2><code>renderToString</code></h2>
<p>Render a server component to a complete HTML string:</p>
<pre><code class="language-typescript">import { renderToString } from &#39;@aihu/server&#39;

const html = await renderToString(async () =&gt; {
  const data = await myLoader(ctx)
  return renderMyComponent(data)
})
</code></pre>
<h2>Client-build elision</h2>
<p>When target is <code>client</code>:</p>
<ul>
<li><code>@agent</code> blocks are removed from the output. The JS contains: <code>// [client build] @agent block elided</code>.</li>
<li><code>$server</code> macro references are removed. The JS contains: <code>// [client build] $server macro reference elided</code>.</li>
<li><code>manifest_json</code> in <code>EmitResult</code> is empty.</li>
</ul>
<p>This ensures zero server-only code reaches the browser bundle.</p>
<h2><code>defineAihuConfig</code> build options</h2>
<pre><code class="language-typescript">defineAihuConfig({
  build: {
    target: &#39;universal&#39;,    // &#39;client&#39; | &#39;server&#39; | &#39;universal&#39;
    outDir: &#39;dist&#39;,         // output directory
    sourcemap: true,        // emit sourcemaps
  },
})
</code></pre>
<h2>SSR with loaders</h2>
<p>Enable SSR per route with <code>ssr: true</code> in the <code>@route</code> block. The server runs the associated <code>defineLoader</code> and injects the result as props before streaming the component:</p>
<pre><code>@route {
  name: users
  ssr: true
}
</code></pre>
<pre><code class="language-typescript">// users.loader.ts
export const loader = defineLoader(async (ctx) =&gt; {
  return { users: await db.users.findMany() }
})
</code></pre>
<p>The loader result is serialized into the SSR payload and dehydrated on the client — no second fetch needed.</p>
`,
  }
}
