/**
 * GENERATED by scripts/sync-template-versions.ts — DO NOT EDIT BY HAND.
 *
 * The dependency ranges `@aihu/cli` writes into a scaffolded project's
 * package.json. Regenerate with:
 *
 *   bun scripts/sync-template-versions.ts
 *
 * `check:template-versions` fails CI when this file disagrees with the
 * workspace versions it is derived from, so a hand edit here does not survive
 * review. Change a version by releasing the package; change the `vite` range
 * in EXTERNAL_RANGES inside the generator.
 */

/** Caret ranges for every published `@aihu/*` / `@aihu-plugin/*` package. */
export const AIHU_DEP_VERSIONS: Readonly<Record<string, string>> = {
  '@aihu/app': '^9.0.0',
  '@aihu/runtime': '^5.0.0',
}

/** Third-party ranges a scaffold pins. See EXTERNAL_RANGES in the generator. */
export const EXTERNAL_DEP_VERSIONS: Readonly<Record<string, string>> = {
  vite: '^6 || ^8',
}

/**
 * The range to write for `name`.
 *
 * THROWS on an unknown name rather than falling back to `'latest'` or `'*'`.
 * A silent fallback is how the string this file exists to delete would come
 * back: a template referencing a package that has been renamed would emit an
 * unpinned dependency and every scaffold would keep working, wrongly.
 */
export function aihuDep(name: string): string {
  const range = AIHU_DEP_VERSIONS[name] ?? EXTERNAL_DEP_VERSIONS[name]
  if (range === undefined) {
    throw new Error(
      `[@aihu/cli] no generated version range for '${name}'. Either the package is not a ` +
        'published workspace package, or dep-versions.ts is stale — run ' +
        '`bun scripts/sync-template-versions.ts`.',
    )
  }
  return range
}
