// AUTO-GENERATED by scripts/gen-cn-conflict-map.ts — DO NOT EDIT.
// Source of truth: aihu-css-core `tokens::conflict_groups()` (the utility
// registry). Regenerate with `bun run gen:cn-map`. Hand-edits will be lost.
//
// Maps a utility class PREFIX to the CSS property group it controls. Two
// classes conflict (last wins) when they resolve to the same group.

/** Prefix → conflict-group key, sorted longest-prefix-first. */
export const CONFLICT_GROUPS: Record<string, string> = {
  'fixture-bb': 'group-b',
  'fixture-a': 'group-a',
}
