#!/usr/bin/env bun
/**
 * Generate the utility stylesheet for this demo using the REAL published
 * `@aihu/css-engine` `compile()` API.
 *
 * NOTE: The AST scanner that auto-discovers `.aihu` utility classes IS now
 * wired through `viteAihuPlugin` → `aihuCompilerPlugin` (the auto-fold path
 * shipped in css-engine v0.5.x). For the canonical wiring, see
 * `examples/css-engine-utility/`. This demo intentionally bypasses
 * `viteAihuPlugin` and lists its classes by hand so it can additionally
 * showcase the `cn()` runtime helper and the `anchorFallback` progressive
 * shim against a stable, hand-rolled stylesheet.
 *
 * Run via `bun run gen:css` (also runs as the `predev` / `prebuild` hook).
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compile } from '@aihu/css-engine'

// Utility classes used across css-engine-demo.aihu (base + every cn() branch).
const CLASSES = [
  'flex',
  'flex-col',
  'gap-2',
  'gap-3',
  'gap-4',
  'p-4',
  'p-6',
  'px-3',
  'px-4',
  'py-2',
  'm-0',
  'rounded-md',
  'rounded-lg',
  'rounded-full',
  'border',
  'border-border',
  'shadow',
  'text-sm',
  'text-lg',
  'text-xl',
  'font-medium',
  'font-semibold',
  'font-bold',
  'bg-surface',
  'bg-accent',
  'text-foreground',
  'text-muted',
  'text-accent-foreground',
  'relative',
]

const css = compile(CLASSES)
const __dirname = dirname(fileURLToPath(import.meta.url))
const out = join(__dirname, 'utilities.generated.css')
writeFileSync(
  out,
  `/* GENERATED by gen-css.ts via @aihu/css-engine compile(). Do not edit. */\n${css}`,
)
console.log(`Wrote ${out} (${CLASSES.length} utilities)`)
