// AUTO-GENERATED by scripts/gen-animations-gallery.ts — DO NOT EDIT.
// Source of truth: aihu-css-core `animations::ANIMATIONS`. Regenerate with
// `bun run gen:animations-gallery` (from packages/css-engine). Hand-edits
// will be lost.

/** Every ported tailwind-animations class name, in the catalog's own sorted
 * order — the demo gallery's render list. */
export const ANIMATION_GALLERY_CLASSES: readonly string[] = [
  "fixture-fade-in",
  "fixture-slide-up"
]
