/**
 * @aihu/magna — beforeCompile SDL pipeline.
 *
 * Implements the SDL validation + typed-binding generation step that runs during
 * the aihu build phase. Gracefully skips when @aihu/magna-gqlmin is absent.
 *
 * Pipeline (per brief):
 *   1. Resolve schemaPath (default 'schema.graphql') against ctx.projectRoot.
 *   2. Try to import @aihu/magna-gqlmin. On failure → warn + untyped=true, return.
 *   3. Check if schema file exists. If not → warn + untyped=true, return.
 *   4. Parse SDL via gqlmin.parseSchema(). On parse error → warn + untyped=true, return.
 *   5. Emit typed bindings to outputPath (default 'src/generated/magna.ts').
 *   6. setBuildFlag(magna.untyped, false).
 *
 * This module is build-time ONLY (uses node:fs). Never imported in browser bundles.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, join } from 'node:path'
import type { MagnaBuildContext } from './types.js'
import { setBuildFlag, writeWarnOnce } from './warnings.js'

interface GqlminModule {
  parseSchema: (sdl: string) => unknown
}

/**
 * Run the beforeCompile SDL pipeline.
 *
 * All failures are handled gracefully — the build is never aborted; instead
 * a warning is recorded and `magna.untyped` is set to `true` so consumers
 * know typed generation was skipped.
 */
export async function beforeCompile(ctx: MagnaBuildContext): Promise<void> {
  const { outputDir, projectRoot } = ctx
  const { options, outputPath } = ctx.magna

  // 1. Resolve schemaPath
  const rawPath = options.schemaPath ?? 'schema.graphql'
  const schemaAbsPath = isAbsolute(rawPath) ? rawPath : join(projectRoot, rawPath)

  // 2. Try to import @aihu/magna-gqlmin
  let gqlmin: GqlminModule
  try {
    // @ts-expect-error — @aihu/magna-gqlmin is optional; graceful-skip when absent
    gqlmin = (await import('@aihu/magna-gqlmin')) as GqlminModule
  } catch {
    writeWarnOnce(
      outputDir,
      'gqlmin not installed; SDL validation skipped. createMagnaResource will use untyped string-template GraphQL.',
    )
    setBuildFlag(outputDir, 'magna.untyped', true)
    return
  }

  // 3. Check if schema file exists
  if (!existsSync(schemaAbsPath)) {
    writeWarnOnce(outputDir, `schema not found at ${schemaAbsPath}; resources will be untyped.`)
    setBuildFlag(outputDir, 'magna.untyped', true)
    return
  }

  // 4. Parse the SDL
  const sdl = readFileSync(schemaAbsPath, 'utf8')
  let _ast: unknown
  try {
    _ast = gqlmin.parseSchema(sdl)
  } catch (err) {
    writeWarnOnce(
      outputDir,
      `SDL parse error in ${schemaAbsPath}: ${(err as Error).message ?? String(err)}; resources will be untyped.`,
    )
    setBuildFlag(outputDir, 'magna.untyped', true)
    return
  }

  // 5. Emit typed bindings
  const absOutputPath = isAbsolute(outputPath) ? outputPath : join(projectRoot, outputPath)
  mkdirSync(dirname(absOutputPath), { recursive: true })
  writeFileSync(
    absOutputPath,
    [
      '// AUTO-GENERATED by @aihu/magna beforeCompile. Do not edit.',
      `// Schema: ${schemaAbsPath}`,
      `// Generated: ${new Date().toISOString()}`,
      '',
      '// Typed bindings will be populated when @aihu/magna-gqlmin codegen is implemented.',
      'export {}',
      '',
    ].join('\n'),
    'utf8',
  )

  // 6. Mark as typed
  setBuildFlag(outputDir, 'magna.untyped', false)
}
