/**
 * GENERATED FILE — do not edit.
 *
 * Playground presets derived from the cookbook corpus: every recipe whose
 * frontmatter carries a `playground:` label lands here. Regenerate with
 * `bun packages/mcp/scripts/build-cookbook-index.ts`; CI diffs this file
 * against a fresh build (scripts/check-cookbook-index.ts).
 */

export interface GeneratedPreset {
  readonly id: string
  readonly label: string
  readonly source: string
}

export const GENERATED_PRESETS: readonly GeneratedPreset[] = [
  {
    id: "agent-weather",
    label: "Agent",
    source: "// agent-weather — agent-surface pattern: prop city + action fetchForecast with expose/describe\n\n@state {\n  let city = prop({\n    default: 'London',\n    describe: 'City name to retrieve weather forecast for',\n    expose: 'read',\n  })\n\n  let forecast = state('')\n  let loading = state(false)\n  let errorMsg = state('')\n\n  const fetchForecast = action(\n    { describe: 'Fetch the latest weather forecast for the current city',\n      expose: 'read write' },\n    async () => {\n        loading = true\n        errorMsg = ''\n        try {\n          const res = await fetch(`/api/weather?city=${encodeURIComponent(city)}`)\n          if (!res.ok) throw new Error(`HTTP ${res.status}`)\n          forecast = await res.text()\n        } catch (e) {\n          errorMsg = e instanceof Error ? e.message : String(e)\n        } finally {\n          loading = false\n        }\n      })\n}\n\n@template {\n  <div class=\"weather-agent\">\n    <h2 class=\"title\">Weather — {city}</h2>\n    <group if={loading}>\n      <p class=\"loading\">Fetching forecast…</p>\n    </group><group elseif={errorMsg}>\n      <p class=\"error\">{errorMsg}</p>\n    </group><group elseif={forecast}>\n      <p class=\"forecast\">{forecast}</p>\n    </group><group else>\n      <p class=\"prompt\">Press Refresh to load forecast.</p>\n    </group>\n    <button on:click={fetchForecast} class=\"refresh-btn\" disabled={loading}>\n      Refresh\n    </button>\n  </div>\n}\n\n@style {\n  .weather-agent { padding: 1.5rem; max-width: 22rem; border: 1px solid var(--border, #ccc); border-radius: 6px; }\n  .title { margin: 0 0 1rem; font-size: 1.2rem; }\n  .loading { color: var(--info, #036); }\n  .error { color: var(--error, #c00); }\n  .forecast { font-size: 1rem; line-height: 1.5; }\n  .prompt { color: var(--muted, #888); font-style: italic; }\n  .refresh-btn { margin-top: 0.75rem; padding: 0.4rem 1rem; cursor: pointer; border: 1px solid var(--border, #ccc); border-radius: 4px; }\n  .refresh-btn:disabled { opacity: 0.5; cursor: not-allowed; }\n}\n",
  },
  {
    id: "aihu-counter",
    label: "Counter",
    source: "// counter — prop count + action increment/decrement/reset\n\n@state {\n  let count = prop({ default: 0 })\n\n  const increment = action(() => { count++ })\n  const decrement = action(() => { count-- })\n  const reset = action(() => { count = 0 })\n}\n\n@template {\n  <section class=\"counter\">\n    <output class=\"count\">{count}</output>\n    <div class=\"controls\">\n      <button on:click={decrement} class=\"btn\">−</button>\n      <button on:click={reset} class=\"btn btn-ghost\">Reset</button>\n      <button on:click={increment} class=\"btn\">+</button>\n    </div>\n  </section>\n}\n\n@style {\n  .counter { display: grid; gap: 0.75rem; padding: 1.5rem; max-width: 14rem; }\n  .count { font-size: 2.5rem; font-variant-numeric: tabular-nums; text-align: center; display: block; }\n  .controls { display: flex; gap: 0.5rem; }\n  .btn { flex: 1; padding: 0.5rem; cursor: pointer; border: 1px solid var(--border, #ccc); border-radius: 4px; }\n  .btn-ghost { background: transparent; }\n}\n",
  },
  {
    id: "aihu-tabs",
    label: "Tabs",
    source: "// tabs — prop tabs + action selectTab, derived selected (active tab)\n\n@state {\n  const tabs = prop({\n    default: [\n        { id: 'overview', label: 'Overview', content: 'Overview panel content.' },\n        { id: 'details', label: 'Details', content: 'Details panel content.' },\n        { id: 'settings', label: 'Settings', content: 'Settings panel content.' },\n      ],\n  })\n\n  let activeId = state('')\n\n  const selected = derived(() => tabs.find(t => t.id === activeId) ?? tabs[0] ?? null)\n\n  onMount(() => {\n      if (tabs.length > 0) activeId = tabs[0].id\n    })\n\n  const selectTab = action((id) => { activeId = id })\n}\n\n@template {\n  <div class=\"tabs-component\">\n    <div class=\"tab-list\" role=\"tablist\">\n      <group each={tab of tabs} key={tab.id}>\n        <button\n          role=\"tab\"\n          class={['tab-btn', activeId === tab.id && 'active']}\n          aria-selected={activeId === tab.id}\n          on:click={() => selectTab(tab.id)}\n        >\n          {tab.label}\n        </button>\n      </group>\n    </div>\n    <div class=\"tab-panel\" role=\"tabpanel\">\n      <group if={selected}>\n        <p>{selected.content}</p>\n      </group><group else>\n        <p class=\"empty\">No tab selected.</p>\n      </group>\n    </div>\n  </div>\n}\n\n@style {\n  .tabs-component { max-width: 32rem; border: 1px solid var(--border, #ccc); border-radius: 6px; overflow: hidden; }\n  .tab-list { display: flex; border-bottom: 1px solid var(--border, #ccc); background: var(--tab-bar-bg, #f5f5f5); }\n  .tab-btn { flex: 1; padding: 0.6rem 0.75rem; background: none; border: none; border-bottom: 3px solid transparent; cursor: pointer; font-size: 0.9rem; }\n  .tab-btn.active { border-bottom-color: var(--accent, #0066cc); color: var(--accent, #0066cc); font-weight: 600; }\n  .tab-panel { padding: 1rem; }\n  .tab-panel p { margin: 0; }\n  .empty { color: var(--muted, #888); font-style: italic; }\n}\n",
  },
  {
    id: "form-validation",
    label: "Form",
    source: "// form-validation — form() with value+validity for form-associated custom element\n\n@state {\n  let value = state('')\n  let touched = state(false)\n\n  form({\n    value: () => value,\n    validity: () => ({ valueMissing: !value.trim(), tooShort: value.trim().length < 2 }),\n  })\n\n  const errorMessage = derived(() => {\n      if (!touched) return ''\n      if (!value.trim()) return 'This field is required.'\n      if (value.trim().length < 2) return 'Must be at least 2 characters.'\n      return ''\n    })\n  const isValid = derived(() => value.trim().length >= 2)\n\n  const onInput = action((e: Event) => {\n      value = e.target.value\n      touched = true\n    })\n  const onBlur = action(() => { touched = true })\n}\n\n@template {\n  <label class=\"form-field\">\n    <span class=\"field-label\">Name <span aria-hidden=\"true\">*</span></span>\n    <input\n      type=\"text\"\n      class={['field-input', touched && !isValid && 'invalid']}\n      value={value}\n      on:input={onInput}\n      on:blur={onBlur}\n      required\n      minlength=\"2\"\n    />\n    <group if={errorMessage}>\n      <span class=\"error-msg\" role=\"alert\">{errorMessage}</span>\n    </group>\n    <group if={isValid}>\n      <span class=\"valid-msg\">Looks good!</span>\n    </group>\n  </label>\n}\n\n@style {\n  .form-field { display: flex; flex-direction: column; gap: 0.3rem; max-width: 20rem; }\n  .field-label { font-size: 0.9rem; font-weight: 600; }\n  .field-input { padding: 0.5rem; border: 1px solid var(--border, #ccc); border-radius: 4px; font-size: 1rem; }\n  .field-input.invalid { border-color: var(--error, #c00); }\n  .error-msg { font-size: 0.8rem; color: var(--error, #c00); }\n  .valid-msg { font-size: 0.8rem; color: var(--success, #080); }\n}\n",
  },
  {
    id: "search-debounce",
    label: "Search",
    source: "// search-debounce — bind:value on input + effect() with 300ms debounce, derived results\n\n@state {\n  let query = state('')\n  let debouncedQuery = state('')\n  let _debounceTimer = null\n\n  effect(() => {\n    if (_debounceTimer !== null) clearTimeout(_debounceTimer)\n    _debounceTimer = setTimeout(() => {\n      debouncedQuery = query\n      _debounceTimer = null\n    }, 300) as unknown as number\n  })\n\n  const results = derived(() => {\n      if (!debouncedQuery.trim()) return []\n      const q = debouncedQuery.toLowerCase()\n      return [\n        'apple', 'apricot', 'banana', 'blueberry', 'cherry',\n        'grape', 'kiwi', 'lemon', 'mango', 'orange', 'peach', 'pear',\n      ].filter(item => item.includes(q))\n    })\n}\n\n@template {\n  <div class=\"search-box\">\n    <label class=\"search-label\">\n      Search fruits\n      <input\n        type=\"search\"\n        class=\"search-input\"\n        bind:value={query}\n        placeholder=\"Type to search…\"\n        aria-label=\"Search fruits\"\n      />\n    </label>\n    <group if={query && results.length === 0}>\n      <p class=\"no-results\">No results for \"<strong>{query}</strong>\"</p>\n    </group><group elseif={results.length > 0}>\n      <ul class=\"result-list\">\n        <group each={item of results} key={item}>\n          <li class=\"result-item\">{item}</li>\n        </group>\n      </ul>\n    </group>\n  </div>\n}\n\n@style {\n  .search-box { max-width: 22rem; padding: 1rem; }\n  .search-label { display: flex; flex-direction: column; gap: 0.4rem; font-size: 0.9rem; font-weight: 500; }\n  .search-input { padding: 0.5rem; border: 1px solid var(--border, #ccc); border-radius: 4px; font-size: 1rem; width: 100%; }\n  .no-results { color: var(--muted, #888); font-size: 0.9rem; margin-top: 0.5rem; }\n  .result-list { list-style: none; padding: 0; margin: 0.5rem 0 0; border: 1px solid var(--border, #ccc); border-radius: 4px; overflow: hidden; }\n  .result-item { padding: 0.4rem 0.75rem; border-bottom: 1px solid var(--border, #eee); font-size: 0.9rem; }\n  .result-item:last-child { border-bottom: none; }\n}\n",
  },
  {
    id: "theme-toggle",
    label: "Theme",
    source: "// theme-toggle — dark/light toggle: provide() for theme + effect() for documentElement class\n\n@state {\n  let theme = state('light')\n\n  provide('theme', theme)\n\n  effect(() => {\n    document.documentElement.classList.toggle('dark', theme === 'dark')\n    document.documentElement.classList.toggle('light', theme === 'light')\n  })\n\n  const toggle = action(() => { theme = theme === 'light' ? 'dark' : 'light' })\n  const setTheme = action((t: 'light' | 'dark') => { theme = t })\n}\n\n@template {\n  <div class=\"theme-toggle\">\n    <button\n      class={['toggle-btn', theme]}\n      on:click={toggle}\n      aria-label={`Switch to ${theme === 'light' ? 'dark' : 'light'} theme`}\n    >\n      {theme === 'light' ? '☀ Light' : '☾ Dark'}\n    </button>\n    <span class=\"current\">Current: {theme}</span>\n  </div>\n}\n\n@style {\n  .theme-toggle { display: flex; align-items: center; gap: 1rem; padding: 0.75rem 1rem; }\n  .toggle-btn { padding: 0.4rem 0.9rem; border: 1px solid var(--border, #ccc); border-radius: 20px; cursor: pointer; font-size: 0.9rem; transition: background 0.2s; }\n  .toggle-btn.light { background: #fff; color: #333; }\n  .toggle-btn.dark { background: #111; color: #eee; border-color: #555; }\n  .current { font-size: 0.8rem; color: var(--muted, #888); }\n}\n",
  },
]
