/**
 * @aihu/server — client-side stubs (v0.6.7)
 *
 * This module provides client-side helpers that call server-action endpoints.
 * These stubs are generated by the $server macro compiler; consumers rarely
 * import them directly.
 *
 * NOTE: This file is client-safe (no Node.js imports). It relies only on the
 * browser `fetch` API.
 */

/**
 * Create a typed client stub that calls a server action via HTTP POST.
 *
 * The generic types carry the wire contract at compile time; at runtime the
 * call is a plain `fetch` to `/server/_actions/<endpoint>`.
 *
 * @param endpoint — The server action endpoint identifier, typically in the
 *   form `"component-id/actionName"`. This is appended to the base path
 *   `/server/_actions/`.
 *
 * @example
 * // Generated by the $server macro:
 * const getUser = createServerCall<[id: string], User>('my-component/getUser')
 * const user = await getUser('42')
 */
export function createServerCall<Args extends unknown[], Return>(
  endpoint: string,
): (...args: Args) => Promise<Return> {
  return async (...args: Args): Promise<Return> => {
    const res = await fetch(`/server/_actions/${endpoint}`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(args),
    })
    if (!res.ok) throw new Error(`Server action failed: ${res.statusText}`)
    return res.json() as Return
  }
}
