/**
 * GENERATED by scripts/sync-template-versions.ts — DO NOT EDIT BY HAND.
 *
 * The dependency ranges `@aihu/cli` writes into a scaffolded project's
 * package.json. Regenerate with:
 *
 *   bun scripts/sync-template-versions.ts
 *
 * `check:template-versions` fails CI when this file disagrees with the
 * workspace versions it is derived from, so a hand edit here does not survive
 * review. Change a version by releasing the package; change the `vite` range
 * in EXTERNAL_RANGES inside the generator.
 */

/** Caret ranges for every published `@aihu/*` / `@aihu-plugin/*` package. */
export const AIHU_DEP_VERSIONS: Readonly<Record<string, string>> = {
  '@aihu-plugin/agent-readiness': '^2.3.0',
  '@aihu-plugin/data': '^2.0.5',
  '@aihu-plugin/drizzle': '^0.1.6',
  '@aihu-plugin/kindly-note': '^0.2.4',
  '@aihu/adapter-cloudflare': '^13.0.0',
  '@aihu/adapter-vercel': '^13.0.0',
  '@aihu/agent': '^0.2.0',
  '@aihu/agent-a2a': '^1.0.1',
  '@aihu/agent-acp': '^0.2.1',
  '@aihu/agent-server': '^0.4.4',
  '@aihu/agent-service': '^0.4.0',
  '@aihu/ai': '^0.1.0',
  '@aihu/app': '^10.0.0',
  '@aihu/arbor': '^4.1.1',
  '@aihu/auth': '^6.0.0',
  '@aihu/cli': '^1.3.0',
  '@aihu/compiler': '^1.3.0',
  '@aihu/context': '^0.2.0',
  '@aihu/css-engine': '^0.6.1',
  '@aihu/editor': '^0.1.2',
  '@aihu/language-server': '^0.4.1',
  '@aihu/magna': '^0.2.7',
  '@aihu/mcp': '^0.2.0',
  '@aihu/plugin': '^0.1.0',
  '@aihu/primitives': '^0.2.3',
  '@aihu/reactive': '^0.2.0',
  '@aihu/router': '^0.5.0',
  '@aihu/runtime': '^6.1.0',
  '@aihu/scraping': '^0.2.0',
  '@aihu/seo': '^1.0.5',
  '@aihu/server': '^0.6.0',
  '@aihu/signals': '^0.5.0',
  '@aihu/store': '^0.1.2',
  '@aihu/tsc': '^0.3.3',
  '@aihu/ui': '^0.1.1',
  '@aihu/use': '^2.0.0',
}

/** Third-party ranges a scaffold pins. See EXTERNAL_RANGES in the generator. */
export const EXTERNAL_DEP_VERSIONS: Readonly<Record<string, string>> = {
  vite: '^6 || ^8',
}

/**
 * The range to write for `name`.
 *
 * THROWS on an unknown name rather than falling back to `'latest'` or `'*'`.
 * A silent fallback is how the string this file exists to delete would come
 * back: a template referencing a package that has been renamed would emit an
 * unpinned dependency and every scaffold would keep working, wrongly.
 */
export function aihuDep(name: string): string {
  const range = AIHU_DEP_VERSIONS[name] ?? EXTERNAL_DEP_VERSIONS[name]
  if (range === undefined) {
    throw new Error(
      `[@aihu/cli] no generated version range for '${name}'. Either the package is not a ` +
        'published workspace package, or dep-versions.ts is stale — run ' +
        '`bun scripts/sync-template-versions.ts`.',
    )
  }
  return range
}
