import { existsSync, readdirSync } from 'node:fs'
import { resolve, join } from 'node:path'
import type { RouteSegment } from './router.ts'

/**
 * Minimal Vite Plugin interface — avoids importing from 'vite' at compile time.
 * `vite` is listed as external in rolldown.config.ts.
 * @internal
 */
interface VitePlugin {
  name: string
  resolveId?: (id: string) => string | null | undefined
  load?: (id: string) => string | null | undefined
  configureServer?: (server: {
    watcher: {
      add(path: string): void
      on(event: string, cb: (path: string) => void): void
    }
    moduleGraph: {
      getModuleById(id: string): { id: string } | undefined
      invalidateModule(mod: { id: string }): void
    }
  }) => void
}

const VIRTUAL_ID = 'virtual:scribe-routes'
const RESOLVED_ID = '\0virtual:scribe-routes'

export interface RouterPluginOptions {
  pagesDir?: string
}

/**
 * Parse a file path (relative to pages dir) into route segments.
 * e.g. "blog/[...all].ts" → [static("blog"), catchall()]
 */
function parseSegments(relPath: string): RouteSegment[] {
  const withoutExt = relPath.replace(/\.[^/]+$/, '')
  const parts = withoutExt.replace(/\\/g, '/').split('/').filter(Boolean)
  return parts.map((part): RouteSegment => {
    if (part.startsWith('[...') && part.endsWith(']')) return { kind: 'catchall' }
    if (part.startsWith('[') && part.endsWith(']')) return { kind: 'param', name: part.slice(1, -1) }
    return { kind: 'static', path: part }
  })
}

/**
 * Convert route segments to a URL pattern string.
 */
function segmentsToPattern(segments: RouteSegment[]): string {
  if (segments.length === 0) return '/'
  return segments
    .map((seg) => (seg.kind === 'static' ? seg.path : seg.kind === 'param' ? `:${seg.name}` : '*'))
    .join('/')
    .replace(/^(?!\/)/, '/')
}

/**
 * Generate the virtual module body for a given list of page files.
 */
function generateVirtualModule(pageFiles: string[], pagesDir: string): string {
  const routes = pageFiles.map((file) => {
    const rel = file.replace(/\\/g, '/').replace(new RegExp(`^.*?${pagesDir}/`), '')
    const segments = parseSegments(rel)
    const pattern = segmentsToPattern(segments)
    return `  {
    pattern: ${JSON.stringify(pattern)},
    segments: ${JSON.stringify(segments)},
    module: () => import(${JSON.stringify(file.replace(/\\/g, '/'))}),
  }`
  })
  return `// AUTO-GENERATED by @scribe/router vite plugin — do not edit\nexport default [\n${routes.join(',\n')}\n];\n`
}

function scanPages(root: string, pagesDir: string): string[] {
  const dir = resolve(root, pagesDir)
  if (!existsSync(dir)) return []
  const results: string[] = []
  function walk(current: string): void {
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const full = join(current, entry.name)
      if (entry.isDirectory()) walk(full)
      else if (entry.isFile() && /\.(ts|js|tsx|jsx)$/.test(entry.name) && !entry.name.startsWith('_'))
        results.push(full)
    }
  }
  walk(dir)
  return results.sort()
}

/**
 * Vite plugin that exposes pages as the virtual module `virtual:scribe-routes`.
 * In dev mode, watches for additions/removals and invalidates the module.
 */
export function viteRouterPlugin(options?: RouterPluginOptions): VitePlugin {
  const pagesDir = options?.pagesDir ?? 'pages'
  let root = process.cwd()
  let cachedModule: string | null = null

  return {
    name: 'scribe-router',

    resolveId(id: string) {
      if (id === VIRTUAL_ID) return RESOLVED_ID
      return null
    },

    load(id: string) {
      if (id !== RESOLVED_ID) return null
      cachedModule ??= generateVirtualModule(scanPages(root, pagesDir), pagesDir)
      return cachedModule
    },

    configureServer(server) {
      const srv = server as unknown as { config?: { root?: string } } & typeof server
      if (srv.config?.root) root = srv.config.root

      const pagesAbsDir = resolve(root, pagesDir)
      server.watcher.add(pagesAbsDir)

      const invalidate = (filePath: string): void => {
        if (!filePath.includes(pagesAbsDir.replace(/\\/g, '/'))) return
        cachedModule = null
        const mod = server.moduleGraph.getModuleById(RESOLVED_ID)
        if (mod) server.moduleGraph.invalidateModule(mod)
      }

      server.watcher.on('add', invalidate)
      server.watcher.on('unlink', invalidate)
    },
  }
}
