#!/usr/bin/env bun
/**
 * canary-catchall-changeset.ts — write an ephemeral catch-all changeset so a
 * canary snapshot versions EVERY publishable package.
 *
 * `changeset version --snapshot canary` only versions packages that appear in
 * the release plan (pending changesets + their dependents). A canary consumer
 * (e.g. fellwork/web) pins the whole @aihu/* family together, so a partial
 * snapshot — some packages at 0.0.0-canary-<sha>, the rest at their stable
 * versions — would silently mix unreleased and released code across package
 * boundaries. This script writes .changeset/canary-snapshot-catchall.md with
 * a `patch` entry for every non-private, non-ignored package under packages/*
 * so the snapshot covers the full publish set.
 *
 * Run BEFORE `changeset version --snapshot canary`. The file is EPHEMERAL:
 * the version run consumes it, and canary CI never commits — nothing lands
 * in history. Deterministic: the package set derives from the checked-out
 * SHA, so every canary publish job generates the identical changeset and
 * therefore the identical release plan.
 *
 * Excluded on purpose:
 *   - packages/_moved/* — frozen legacy-name stubs (@aihu/data,
 *     @aihu/agent-readiness at 1.x); a canary of a moved stub is meaningless.
 *   - the packages/<host>/npm/<platform> platform packages — not workspace
 *     members; they are synced separately by scripts/stamp-platform-versions.ts.
 *   - private packages and the .changeset/config.json `ignore` list.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const OUT = join(ROOT, '.changeset', 'canary-snapshot-catchall.md')

const config = JSON.parse(readFileSync(join(ROOT, '.changeset', 'config.json'), 'utf8'))
const ignore = new Set<string>(config.ignore ?? [])

const names: string[] = []
for (const dir of readdirSync(join(ROOT, 'packages'), { withFileTypes: true })) {
  if (!dir.isDirectory()) continue
  if (dir.name === '_moved' || dir.name === 'templates') continue
  const pkgPath = join(ROOT, 'packages', dir.name, 'package.json')
  if (!existsSync(pkgPath)) continue
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'))
  if (pkg.private === true) continue
  if (ignore.has(pkg.name)) continue
  names.push(pkg.name)
}
names.sort()

if (names.length === 0) {
  console.error(
    '✗ found no publishable packages under packages/* — refusing to write an empty catch-all',
  )
  process.exit(1)
}

const frontMatter = names.map((n) => `'${n}': patch`).join('\n')
writeFileSync(
  OUT,
  `---\n${frontMatter}\n---\n\nCanary snapshot catch-all — ephemeral, generated by scripts/canary-catchall-changeset.ts; never commit this file.\n`,
)
console.log(`✔ wrote ${OUT} covering ${names.length} packages`)
