#!/usr/bin/env bun
/**
 * Dogfood `@aihu/css-engine` — generate the utility layer for docs-next from the
 * REAL published `compile()` API (the same Rust `aihu-css-compile` binary the
 * framework ships). We use ONLY layout / spacing / typography utilities here;
 * all COLOR comes from the hand-authored design-token layer in
 * `src/styles/tokens.css`, so the two systems compose without coupling on token
 * names. Runs as the `predev` / `prebuild` hook; output is git-ignored.
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { compile } from '@aihu/css-engine'

// Utility classes actually used across the docs-next templates.
const CLASSES = [
  'flex',
  'flex-col',
  'items-center',
  'items-start',
  'justify-between',
  'justify-center',
  'gap-1',
  'gap-2',
  'gap-3',
  'gap-4',
  'gap-6',
  'p-4',
  'p-6',
  'px-3',
  'px-4',
  'py-2',
  'm-0',
  'rounded-md',
  'rounded-lg',
  'rounded-full',
  'text-sm',
  'text-lg',
  'text-xl',
  'font-medium',
  'font-semibold',
  'font-bold',
  'relative',
  'w-full',
]

const css = compile(CLASSES)
const __dirname = dirname(fileURLToPath(import.meta.url))
const out = join(__dirname, 'src', 'styles', 'utilities.generated.css')
writeFileSync(
  out,
  `/* GENERATED by gen-css.ts via @aihu/css-engine compile(). Do not edit. */\n${css}`,
)
console.log(`Wrote ${out} (${CLASSES.length} utilities via @aihu/css-engine)`)
