/**
 * Full docs-site build script.
 *
 * Steps:
 *   1. Read every `docs/site/*.md` from the repo root
 *   2. Render Markdown → HTML with `marked`
 *   3. Write `src/content.ts` with a `window.__DOCS__` map
 *   4. Run `rolldown -c rolldown.config.ts` to bundle the scribe components
 *
 * Usage:
 *   bun run build.ts
 */

import { execFileSync } from 'node:child_process'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { basename, extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { marked } from 'marked'

const __dir = fileURLToPath(new URL('.', import.meta.url))
const docsDir = join(__dir, '../../docs/site')
const contentOut = join(__dir, 'src/content.ts')

// ── 1. Collect all .md files from docs/site/ ─────────────────────

const files = (await readdir(docsDir)).filter((f) => extname(f) === '.md').sort()

console.log(`Found ${files.length} Markdown files in docs/site/`)

// ── 2. Render each file ──────────────────────────────────────────

interface DocPage {
  id: string
  title: string
  html: string
}

const pages: DocPage[] = []

for (const file of files) {
  const id = basename(file, '.md')
  const source = await readFile(join(docsDir, file), 'utf8')
  const html = await marked.parse(source, { gfm: true, breaks: false })

  // Extract title from first H1
  const titleMatch = source.match(/^#\s+(.+)$/m)
  const title = titleMatch ? titleMatch[1].trim() : id

  // Escape template-literal special chars so the generated TS is valid
  const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${')
  pages.push({ id, title, html: escaped })
  console.log(`  ✓ ${file} → "${title}"`)
}

// ── 3. Write src/content.ts ──────────────────────────────────────

const entries = pages
  .map(
    (p) =>
      `  '${p.id}': {\n    title: '${p.title.replace(/'/g, "\\'")}',\n    html: \`${p.html}\`,\n  }`,
  )
  .join(',\n')

const contentTs = `/**
 * Pre-rendered Markdown pages — generated by build.ts.
 * Do not edit directly; run \`bun run build\` to regenerate.
 */

declare global {
  interface Window {
    __DOCS__: Record<string, { title: string; html: string }>
  }
}

window.__DOCS__ = {
${entries}
}
`

await writeFile(contentOut, contentTs, 'utf8')
console.log(`\nWrote src/content.ts (${pages.length} pages)`)

// ── 4. Bundle with rolldown ──────────────────────────────────────

console.log('\nBundling with rolldown…')
// Use execFileSync with array args (no shell) to avoid injection risk
execFileSync(
  process.execPath, // bun
  ['x', 'rolldown', '-c', 'rolldown.config.ts'],
  { cwd: __dir, stdio: 'inherit' },
)
console.log('\n✓ Build complete → dist/')
