#!/usr/bin/env bun
/**
 * gen-cn-conflict-map.ts — generate the `cn()` conflict map (Plan 3 Task 9).
 *
 * The conflict map is GENERATED from the utility registry, never hand-written,
 * so it can never drift from the compile-time utility table. We invoke the Rust
 * engine binary (`aihu-css-compile --dump-conflict-groups`), which serializes
 * `tokens::conflict_groups()` — the same prefix→property data the emitter uses —
 * and write a compact TS module the runtime imports.
 *
 * Run: `bun run gen:cn-map` (wired into the package build before rolldown).
 */
import { execFileSync } from 'node:child_process'
import { existsSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(__dirname, '..')
const repoRoot = resolve(pkgRoot, '../..')

function resolveBinary(): string {
  const ext = process.platform === 'win32' ? '.exe' : ''
  const candidates = [
    resolve(repoRoot, 'target/release', `aihu-css-compile${ext}`),
    resolve(repoRoot, 'target/debug', `aihu-css-compile${ext}`),
  ]
  for (const c of candidates) {
    if (existsSync(c)) return c
  }
  throw new Error(
    `aihu-css-compile binary not found. Run \`cargo build --release -p aihu-css-core\` first. Checked: ${candidates.join(', ')}`,
  )
}

const bin = resolveBinary()
const json = execFileSync(bin, ['--dump-conflict-groups'], { encoding: 'utf-8' })
const groups = JSON.parse(json) as Array<[string, string]>

// Compact serialization: a flat `{ prefix: group }` record. Sorted by prefix
// length DESC so the runtime's longest-prefix match is unambiguous.
groups.sort((a, b) => b[0].length - a[0].length)
const entries = groups.map(([prefix, group]) => `  '${prefix}': '${group}',`).join('\n')

const out = `// AUTO-GENERATED by scripts/gen-cn-conflict-map.ts — DO NOT EDIT.
// Source of truth: aihu-css-core \`tokens::conflict_groups()\` (the utility
// registry). Regenerate with \`bun run gen:cn-map\`. Hand-edits will be lost.
//
// Maps a utility class PREFIX to the CSS property group it controls. Two
// classes conflict (last wins) when they resolve to the same group.

/** Prefix → conflict-group key, sorted longest-prefix-first. */
export const CONFLICT_GROUPS: Record<string, string> = {
${entries}
}
`

const target = resolve(pkgRoot, 'src/runtime/cn-conflict-map.generated.ts')
writeFileSync(target, out)
console.log(`  generated ${groups.length} conflict-group entries → ${target}`)
