#!/usr/bin/env bun
/**
 * gen-animations-gallery.ts — generate the Storybook demo gallery's data
 * (tailwind-animations port doc, Track A Slice 14: "docs + demo gallery
 * rendering all 78 [animations]... real visual regression net").
 *
 * The gallery lives in `apps/storybook/src/stories/animations-gallery.stories.ts`
 * — a PLAIN HTML story, not a compiled `.aihu` SFC, so its utility classes are
 * never scanned/compiled by Storybook's `aihuCompilerPlugin` (that plugin only
 * processes `.aihu` files — see `.storybook/main.ts`'s doc comment). This
 * script pre-compiles the CSS at generation time instead, invoking the Rust
 * engine binary directly (same pattern as `gen-cn-conflict-map.ts` /
 * `gen-style-packs.ts`):
 *
 *   --dump-animation-classes     → JSON array of every `animations::ANIMATIONS`
 *                                   class name (the gallery's render list)
 *   --dump-animation-gallery-css → the compiled CSS for all of them, PLUS the
 *                                   reduced-motion guard (Flat-mode
 *                                   `compile_classes` alone omits the guard —
 *                                   it's only appended in `OutputMode::Scoped`,
 *                                   the SFC path a plain HTML story never runs)
 *
 * Both are derived from `animations::ANIMATIONS` at generation time, so the
 * gallery can never drift from the real catalog — no hand-maintained class
 * list, the same discipline Slice 10's `inventory_is_complete` gate uses.
 *
 * Run: `bun run gen:animations-gallery` (from packages/css-engine).
 *   bun scripts/gen-animations-gallery.ts --check  # CI: fail if stale
 *
 * FIXTURE-SCAN MODE (C-FEL-GATE-WIRING-RUNS, same shape as check-moon-graph.ts's
 * `MOON_GRAPH_ROOT` / gen-cn-conflict-map.ts's `CN_MAP_TARGET`).
 * `ANIMATIONS_GALLERY_CSS_TARGET` / `ANIMATIONS_GALLERY_CLASSES_TARGET` repoint
 * the `--check` comparison at different committed files instead of the real
 * generated targets. `ANIMATIONS_GALLERY_CLASSES_JSON` /
 * `ANIMATIONS_GALLERY_CSS_DUMP`, separately, repoint the INPUT: instead of
 * invoking the Rust binary, read committed fixture files holding the same
 * `--dump-animation-classes` / `--dump-animation-gallery-css` output shapes.
 * Load-bearing, not cosmetic, same reason as gen-cn-conflict-map.ts's
 * `CN_MAP_DUMP_JSON` — check-gate-wiring.ts's own `gate-wiring` CI job runs
 * with no Rust toolchain, so a fixture that shelled out to the real binary
 * would throw on both its red and green runs.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(__dirname, '..')
const repoRoot = resolve(pkgRoot, '../..')

function resolveBinary(): string {
  const ext = process.platform === 'win32' ? '.exe' : ''
  const candidates = [
    resolve(repoRoot, 'target/release', `aihu-css-compile${ext}`),
    resolve(repoRoot, 'target/debug', `aihu-css-compile${ext}`),
  ]
  for (const c of candidates) {
    if (existsSync(c)) return c
  }
  throw new Error(
    `aihu-css-compile binary not found. Run \`cargo build --release -p aihu-css-core\` first. Checked: ${candidates.join(', ')}`,
  )
}

const classesJson = process.env.ANIMATIONS_GALLERY_CLASSES_JSON
  ? readFileSync(resolve(repoRoot, process.env.ANIMATIONS_GALLERY_CLASSES_JSON), 'utf8')
  : execFileSync(resolveBinary(), ['--dump-animation-classes'], { encoding: 'utf-8' })
const classes = JSON.parse(classesJson) as string[]
const css = process.env.ANIMATIONS_GALLERY_CSS_DUMP
  ? readFileSync(resolve(repoRoot, process.env.ANIMATIONS_GALLERY_CSS_DUMP), 'utf8')
  : execFileSync(resolveBinary(), ['--dump-animation-gallery-css'], { encoding: 'utf-8' })

const storiesDir = resolve(repoRoot, 'apps/storybook/src/stories')
const cssTarget = process.env.ANIMATIONS_GALLERY_CSS_TARGET
  ? resolve(repoRoot, process.env.ANIMATIONS_GALLERY_CSS_TARGET)
  : resolve(storiesDir, 'animations-gallery.generated.css')
const classesTarget = process.env.ANIMATIONS_GALLERY_CLASSES_TARGET
  ? resolve(repoRoot, process.env.ANIMATIONS_GALLERY_CLASSES_TARGET)
  : resolve(storiesDir, 'animations-gallery.generated.ts')

const classesOut = `// AUTO-GENERATED by scripts/gen-animations-gallery.ts — DO NOT EDIT.
// Source of truth: aihu-css-core \`animations::ANIMATIONS\`. Regenerate with
// \`bun run gen:animations-gallery\` (from packages/css-engine). Hand-edits
// will be lost.

/** Every ported tailwind-animations class name, in the catalog's own sorted
 * order — the demo gallery's render list. */
export const ANIMATION_GALLERY_CLASSES: readonly string[] = ${JSON.stringify(classes, null, 2)}
`

const check = process.argv.includes('--check')

if (check) {
  const existingCss = existsSync(cssTarget) ? readFileSync(cssTarget, 'utf8') : ''
  const existingClasses = existsSync(classesTarget) ? readFileSync(classesTarget, 'utf8') : ''
  if (existingCss !== css || existingClasses !== classesOut) {
    console.error(
      `gen-animations-gallery: ${cssTarget} / ${classesTarget} are stale — run \`bun run gen:animations-gallery\` and commit the result.`,
    )
    process.exit(1)
  }
  console.log(`  animations-gallery generated files up to date (${classes.length} animations)`)
} else {
  writeFileSync(cssTarget, css)
  writeFileSync(classesTarget, classesOut)
  console.log(`  generated ${classes.length} animation entries → ${cssTarget}, ${classesTarget}`)
}
