#!/usr/bin/env bun
/**
 * gen-cn-conflict-map.ts — generate the `cn()` conflict map (Plan 3 Task 9).
 *
 * The conflict map is GENERATED from the utility registry, never hand-written,
 * so it can never drift from the compile-time utility table. We invoke the Rust
 * engine binary (`aihu-css-compile --dump-conflict-groups`), which serializes
 * `tokens::conflict_groups()` — the same prefix→property data the emitter uses —
 * and write a compact TS module the runtime imports.
 *
 * Run: `bun run gen:cn-map` (wired into the package build before rolldown).
 *   bun scripts/gen-cn-conflict-map.ts --check  # CI: fail if stale
 *
 * Previously only ran at `prepublishOnly` with no CI drift check — a Rust
 * `conflict_groups()` edit (e.g. the tailwind-animations port's `animate-*`
 * entries) could land and ship without ever regenerating the committed map,
 * silently missing from every `cn()` call until the next publish. `--check`
 * closes that gap; wire it into `check:ci`.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(__dirname, '..')
const repoRoot = resolve(pkgRoot, '../..')

function resolveBinary(): string {
  const ext = process.platform === 'win32' ? '.exe' : ''
  const candidates = [
    resolve(repoRoot, 'target/release', `aihu-css-compile${ext}`),
    resolve(repoRoot, 'target/debug', `aihu-css-compile${ext}`),
  ]
  for (const c of candidates) {
    if (existsSync(c)) return c
  }
  throw new Error(
    `aihu-css-compile binary not found. Run \`cargo build --release -p aihu-css-core\` first. Checked: ${candidates.join(', ')}`,
  )
}

const bin = resolveBinary()
const json = execFileSync(bin, ['--dump-conflict-groups'], { encoding: 'utf-8' })
const groups = JSON.parse(json) as Array<[string, string]>

// Compact serialization: a flat `{ prefix: group }` record. Sorted by prefix
// length DESC so the runtime's longest-prefix match is unambiguous. Keys are
// quoted ONLY when not a valid bare identifier (i.e. contain `-`), matching the
// repo formatter (biome) so the committed file never drifts on re-format.
groups.sort((a, b) => b[0].length - a[0].length)
const needsQuote = (k: string): boolean => !/^[A-Za-z_$][\w$]*$/.test(k)
const key = (k: string): string => (needsQuote(k) ? `'${k}'` : k)
const entries = groups.map(([prefix, group]) => `  ${key(prefix)}: '${group}',`).join('\n')

const out = `// AUTO-GENERATED by scripts/gen-cn-conflict-map.ts — DO NOT EDIT.
// Source of truth: aihu-css-core \`tokens::conflict_groups()\` (the utility
// registry). Regenerate with \`bun run gen:cn-map\`. Hand-edits will be lost.
//
// Maps a utility class PREFIX to the CSS property group it controls. Two
// classes conflict (last wins) when they resolve to the same group.

/** Prefix → conflict-group key, sorted longest-prefix-first. */
export const CONFLICT_GROUPS: Record<string, string> = {
${entries}
}
`

const target = resolve(pkgRoot, 'src/runtime/cn-conflict-map.generated.ts')
const check = process.argv.includes('--check')

if (check) {
  const existing = existsSync(target) ? readFileSync(target, 'utf8') : ''
  if (existing !== out) {
    console.error(
      `gen-cn-conflict-map: ${target} is stale — run \`bun run gen:cn-map\` and commit the result.`,
    )
    process.exit(1)
  }
  console.log(`  cn-conflict-map.generated.ts up to date (${groups.length} entries)`)
} else {
  writeFileSync(target, out)
  console.log(`  generated ${groups.length} conflict-group entries → ${target}`)
}
