#!/usr/bin/env bun
/**
 * gen-cn-conflict-map.ts — generate the `cn()` conflict map (Plan 3 Task 9).
 *
 * The conflict map is GENERATED from the utility registry, never hand-written,
 * so it can never drift from the compile-time utility table. We invoke the Rust
 * engine binary (`aihu-css-compile --dump-conflict-groups`), which serializes
 * `tokens::conflict_groups()` — the same prefix→property data the emitter uses —
 * and write a compact TS module the runtime imports.
 *
 * Run: `bun run gen:cn-map` (wired into the package build before rolldown).
 *   bun scripts/gen-cn-conflict-map.ts --check  # CI: fail if stale
 *
 * Previously only ran at `prepublishOnly` with no CI drift check — a Rust
 * `conflict_groups()` edit (e.g. the tailwind-animations port's `animate-*`
 * entries) could land and ship without ever regenerating the committed map,
 * silently missing from every `cn()` call until the next publish. `--check`
 * closes that gap; wire it into `check:ci`.
 *
 * FIXTURE-SCAN MODE (C-FEL-GATE-WIRING-RUNS, same shape as check-moon-graph.ts's
 * `MOON_GRAPH_ROOT`). `CN_MAP_TARGET` repoints the `--check` comparison at a
 * different committed file instead of the real generated target; it changes
 * WHERE the gate reads and nothing else. `CN_MAP_DUMP_JSON`, separately,
 * repoints the INPUT: instead of invoking the Rust binary, read a committed
 * fixture file holding the same `--dump-conflict-groups` JSON shape. This one
 * is load-bearing, not cosmetic — check-gate-wiring.ts's own `gate-wiring` CI
 * job runs with no `bun install`, no build, no Rust (deliberately, so it stays
 * cheap and runs on every draft push; see that job's own comment in
 * plan-a.yml), so a fixture proof that shelled out to the real binary would
 * throw "binary not found" on BOTH its red and green runs — indiscriminate,
 * not proven. Together, both env vars let the negative-fixture proof exercise
 * only the comparison logic, hermetically, with no Rust toolchain needed.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(__dirname, '..')
const repoRoot = resolve(pkgRoot, '../..')

function resolveBinary(): string {
  const ext = process.platform === 'win32' ? '.exe' : ''
  const candidates = [
    resolve(repoRoot, 'target/release', `aihu-css-compile${ext}`),
    resolve(repoRoot, 'target/debug', `aihu-css-compile${ext}`),
  ]
  for (const c of candidates) {
    if (existsSync(c)) return c
  }
  throw new Error(
    `aihu-css-compile binary not found. Run \`cargo build --release -p aihu-css-core\` first. Checked: ${candidates.join(', ')}`,
  )
}

/**
 * Bounded spawn. An unbounded `execFileSync` against this binary is the same
 * hang that stalled an `apps/docs` build for 10 minutes at 0% CPU (see the
 * spawn-bounds note in `packages/css-engine/src/index.ts`): with no timer armed
 * spawnSync's uv loop blocks in kevent with no deadline, forever. This dump
 * completes in milliseconds, so 60 s is a generous ceiling that still turns a
 * wedged generator into a fast, named failure.
 */
const DUMP_SPAWN_OPTS = {
  encoding: 'utf-8',
  timeout: 60_000,
  maxBuffer: 64 * 1024 * 1024,
  killSignal: 'SIGKILL',
} as const

const json = process.env.CN_MAP_DUMP_JSON
  ? readFileSync(resolve(repoRoot, process.env.CN_MAP_DUMP_JSON), 'utf8')
  : execFileSync(resolveBinary(), ['--dump-conflict-groups'], DUMP_SPAWN_OPTS)
const groups = JSON.parse(json) as Array<[string, string]>

// Compact serialization: a flat `{ prefix: group }` record. Sorted by prefix
// length DESC so the runtime's longest-prefix match is unambiguous. Keys are
// quoted ONLY when not a valid bare identifier (i.e. contain `-`), matching the
// repo formatter (biome) so the committed file never drifts on re-format.
groups.sort((a, b) => b[0].length - a[0].length)
const needsQuote = (k: string): boolean => !/^[A-Za-z_$][\w$]*$/.test(k)
const key = (k: string): string => (needsQuote(k) ? `'${k}'` : k)
const entries = groups.map(([prefix, group]) => `  ${key(prefix)}: '${group}',`).join('\n')

const out = `// AUTO-GENERATED by scripts/gen-cn-conflict-map.ts — DO NOT EDIT.
// Source of truth: aihu-css-core \`tokens::conflict_groups()\` (the utility
// registry). Regenerate with \`bun run gen:cn-map\`. Hand-edits will be lost.
//
// Maps a utility class PREFIX to the CSS property group it controls. Two
// classes conflict (last wins) when they resolve to the same group.

/** Prefix → conflict-group key, sorted longest-prefix-first. */
export const CONFLICT_GROUPS: Record<string, string> = {
${entries}
}
`

const target = process.env.CN_MAP_TARGET
  ? resolve(repoRoot, process.env.CN_MAP_TARGET)
  : resolve(pkgRoot, 'src/runtime/cn-conflict-map.generated.ts')
const check = process.argv.includes('--check')

if (check) {
  const existing = existsSync(target) ? readFileSync(target, 'utf8') : ''
  if (existing !== out) {
    console.error(
      `gen-cn-conflict-map: ${target} is stale — run \`bun run gen:cn-map\` and commit the result.`,
    )
    process.exit(1)
  }
  console.log(`  cn-conflict-map.generated.ts up to date (${groups.length} entries)`)
} else {
  writeFileSync(target, out)
  console.log(`  generated ${groups.length} conflict-group entries → ${target}`)
}
