import { rm, mkdir, cp } from 'node:fs/promises'
import { resolve as resolvePath, join } from 'node:path'
import type { ScribeAdapter, AdapterContext } from '@scribe/app'

export interface VercelAdapterOptions {
  /**
   * Edge Function runtime.
   * - 'edge': Vercel Edge Runtime (V8 isolates, global deployment) — default
   * - 'serverless': Node.js serverless function (regional)
   */
  runtime?: 'edge' | 'serverless'
  /**
   * Vercel Build Output API output directory.
   * Default: '.vercel/output' (relative to project root)
   */
  outputDir?: string
  /**
   * Node.js version for serverless runtime.
   * Only used when runtime === 'serverless'.
   * Default: 'nodejs18.x'
   */
  nodeVersion?: string
}

function generateEdgeFunctionEntry(): string {
  return [
    '// AUTO-GENERATED by @scribe/adapter-vercel — do not edit',
    '// Vercel Edge Function entry — SPA mode',
    '//',
    '// In SPA mode (V0), this function handles /api/** routes only.',
    '// All page requests are served by Vercel CDN from static/index.html.',
    '// For SSR mode, upgrade to @scribe/adapter-vercel with ssr: true (V1+).',
    '',
    'export default async function handler(request) {',
    '  const url = new URL(request.url)',
    "  if (!url.pathname.startsWith('/api/')) {",
    "    return new Response('Not Found', { status: 404 })",
    '  }',
    "  return new Response('API route not implemented', { status: 501 })",
    '}',
    '',
    "export const config = { runtime: 'edge' }",
  ].join('\n') + '\n'
}

function generateServerlessFunctionEntry(): string {
  return [
    '// AUTO-GENERATED by @scribe/adapter-vercel — do not edit',
    '// Vercel Serverless Function entry — SPA mode',
    '',
    'export default async function handler(request, response) {',
    '  const host = request.headers.host ?? "localhost"',
    '  const url = new URL(request.url, `https://${host}`)',
    "  if (!url.pathname.startsWith('/api/')) {",
    '    response.status(404).send("Not Found")',
    '    return',
    '  }',
    '  response.status(501).send("API route not implemented")',
    '}',
  ].join('\n') + '\n'
}

function generateVcConfig(runtime: 'edge' | 'serverless', nodeVersion: string): string {
  if (runtime === 'edge') {
    return JSON.stringify({ runtime: 'edge', entrypoint: 'index.js' }, null, 2) + '\n'
  }
  return (
    JSON.stringify(
      { runtime: nodeVersion, handler: 'index.js', maxDuration: 10 },
      null,
      2,
    ) + '\n'
  )
}

function generateConfigJson(): string {
  const routes = [
    {
      src: '^/assets/(.*)$',
      headers: { 'cache-control': 'public, max-age=31536000, immutable' },
      continue: true,
    },
    {
      src: '^/api/(.*)$',
      dest: '/index.func',
    },
    {
      src: '^/(.*)$',
      dest: '/static/index.html',
    },
  ]
  return JSON.stringify({ version: 3, routes }, null, 2) + '\n'
}

/**
 * Vercel adapter for scribe (Build Output API v3).
 *
 * Copies static assets to `.vercel/output/static/`, writes an Edge or
 * Serverless function entry, and emits the `config.json` routes manifest.
 *
 * @example
 * // scribe.config.ts
 * import { defineConfig } from '@scribe/app'
 * import { vercel } from '@scribe/adapter-vercel'
 *
 * export default defineConfig({
 *   adapter: vercel(),
 * })
 */
export function vercel(options?: VercelAdapterOptions): ScribeAdapter {
  return {
    name: 'vercel',

    async adapt(context: AdapterContext): Promise<void> {
      const runtime = options?.runtime ?? 'edge'
      const nodeVersion = options?.nodeVersion ?? 'nodejs18.x'
      const outputDir = resolvePath(
        context.root,
        options?.outputDir ?? '.vercel/output',
      )

      // Step 1 — Clean output directory (prevents stale files from prior builds)
      await rm(outputDir, { recursive: true, force: true })
      await mkdir(outputDir, { recursive: true })

      // Step 2 — Copy static assets from Vite outDir → .vercel/output/static/
      const staticDir = join(outputDir, 'static')
      await mkdir(staticDir, { recursive: true })
      await cp(context.outDir, staticDir, { recursive: true, force: true })
      console.log(`[@scribe/adapter-vercel] Copied static assets → ${staticDir}`)

      // Step 3 — Write Edge/Serverless function entry
      const funcDir = join(outputDir, 'functions', 'index.func')
      await mkdir(funcDir, { recursive: true })

      const entryContent =
        runtime === 'edge'
          ? generateEdgeFunctionEntry()
          : generateServerlessFunctionEntry()
      await context.writeFile(join(funcDir, 'index.js'), entryContent)

      // Step 4 — Write .vc-config.json
      const vcConfig = generateVcConfig(runtime, nodeVersion)
      await context.writeFile(join(funcDir, '.vc-config.json'), vcConfig)
      console.log(
        `[@scribe/adapter-vercel] Wrote function entry (${runtime} runtime) → ${funcDir}`,
      )

      // Step 5 — Write config.json (Build Output API v3 routes)
      const configJson = generateConfigJson()
      await context.writeFile(join(outputDir, 'config.json'), configJson)

      console.log(`[@scribe/adapter-vercel] Build complete → ${outputDir}`)
      console.log(
        `[@scribe/adapter-vercel] Deploy with: vercel deploy --prebuilt`,
      )
    },
  }
}
